// DO NOT EDIT THIS FILE!
// It has been auto-generated from `codegen/templates/src/mod.rs.jinja`
// using the configuration file `codegen/configs/dst_box.toml`.

//! TODO: Is this useful?
//!
//! TODO: Rename to `rtrb::boxed`?
//!
//! In contrast to [`rtrb::arc`](crate::arc), this provides a [`RingBuffer`]
//! that is *not* automatically dropped when both its [`Producer`] and its [`Consumer`]
//! go out of scope.
//!
//! *See the [crate-level documentation](crate) for information about the available options.*
//!
//! # Usage
//!
//! A [`RingBuffer`] can be created with [`RingBuffer::new()`].
//! After that, a (single) [`Producer`] for writing into the ring buffer can be created with
//! [`RingBuffer::producer()`],
//! and a (single) [`Consumer`] for reading from the ring buffer can be created with
//! [`RingBuffer::consumer()`].
//!
//! [`RingBuffer::new_at()`] can be used to create a `RingBuffer` in pre-allocated memory.
//! [`RingBuffer::from_raw_parts()`] can be used to get access to a `RingBuffer`
//! that has been created at a given memory address.
//! These functions allow usage with dynamic capacity in combination with shared memory
//! (and pre-allocated memory in general), see the `shared-memory-dst` example.
//!
//! # Examples
//!
//! Moving single elements into and out of a queue with
//! [`Producer::push()`] and [`Consumer::pop()`], respectively:
//!
//! ```
//! use rtrb::dst_box::{RingBuffer, PushError, PopError};
//!
//! let rb = RingBuffer::new(2);
//! let mut producer = rb.producer().unwrap();
//! let mut consumer = rb.consumer().unwrap();
//!
//! std::thread::scope(|s| {
//!     # #[cfg(not(miri))]
//!     s.spawn(move || {
//!         std::thread::sleep(std::time::Duration::from_secs(1));
//!         assert_eq!(consumer.pop(), Ok(10));
//!         assert_eq!(consumer.pop(), Ok(20));
//!         assert_eq!(consumer.pop(), Err(PopError::Empty));
//!     });
//!
//!     assert_eq!(producer.push(10), Ok(()));
//!     assert_eq!(producer.push(20), Ok(()));
//!     assert_eq!(producer.push(30), Err(PushError::Full(30)));
//! });
//! ```
//!
//! See the documentation of the [`chunks#examples`] module
//! for examples that write/read multiple items at once.
//! See also:
//!
//!   * [`Producer::write_chunk()`]
//!   * [`Producer::write_chunk_uninit()`]
//!   * [`Producer::push_partial_slice()`] (if `T: Copy`)
//!   * [`Producer::push_entire_slice()`] (if `T: Copy`)
//!
//!   * [`Consumer::read_chunk()`]
//!   * [`Consumer::pop_partial_slice()`] (if `T: Copy`)
//!   * [`Consumer::pop_partial_slice_uninit()`] (if `T: Copy`)
//!   * [`Consumer::pop_entire_slice()`] (if `T: Copy`)
//!   * [`Consumer::pop_entire_slice_uninit()`] (if `T: Copy`)

mod ring_buffer;
pub use ring_buffer::RingBuffer;
mod producer;
pub use producer::Producer;
mod consumer;
pub use consumer::Consumer;
pub mod chunks;

// This is used in the documentation.
#[allow(unused_imports)]
use chunks::WriteChunkUninit;

/// Error type for [`Consumer::peek()`].
#[doc(inline)]
pub use crate::PeekError;

/// Error type for [`Consumer::pop()`].
#[doc(inline)]
pub use crate::PopError;

/// Error type for [`Producer::push()`].
#[doc(inline)]
pub use crate::PushError;

/// Error type for [`Producer::write_chunk()`], [`Producer::write_chunk_uninit()`]
/// and [`Consumer::read_chunk()`].
///
/// To get the maximum number of available slots beforehand
/// (and therefore avoid this error), use
/// [`Producer::slots()`] and [`Consumer::slots()`],
/// respectively.
#[doc(inline)]
pub use crate::ChunkError;

/// Extension trait providing a [`copy_to_uninit()`](CopyToUninit::copy_to_uninit)
/// method on built-in slices.
///
/// This can be used to safely copy data to the
/// slices returned from [`WriteChunkUninit::as_mut_slices()`].
///
/// To use this, the trait has to be brought into scope, e.g. with:
///
/// ```
/// use rtrb::dst_box::CopyToUninit as _;
/// ```
#[doc(inline)]
pub use crate::CopyToUninit;
