// DO NOT EDIT THIS FILE!
// It has been auto-generated from `codegen/templates/src/ring_buffer.rs.jinja`
// using the configuration file `codegen/configs/dst_box.toml`.

use core::cell::UnsafeCell;
use core::mem::MaybeUninit;

use crate::atomic::*;
// Padded indices to avoid false sharing.
use crate::CachePadded;

use super::{Consumer, Producer};

const HAS_PRODUCER: u8 = 0b10000000;
const HAS_CONSUMER: u8 = 0b01000000;

dst_ring_buffer_instantiation! {
/// A bounded single-producer single-consumer (SPSC) queue.
///
/// Elements can be written with a [`Producer`] and read with a [`Consumer`],
/// which can be obtained with [`RingBuffer::producer()`]
/// and [`RingBuffer::consumer()`], respectively.
///
/// [`RingBuffer::new()`] automatically allocates memory on the heap.
/// To work with pre-allocated memory, [`RingBuffer::new_at()`] can be used.
///
/// *See also the [module-level documentation](crate::dst_box).*
#[derive(Debug)]
pub struct RingBuffer<T> {
    head: CachePadded<AtomicUsize>,
    tail: CachePadded<AtomicUsize>,
    flags: AtomicU8,
    /// Storage for the ring buffer elements (dynamically sized).
    ///
    /// This must be in an `UnsafeCell` because both producer and consumer
    /// have a (non-mutable) reference to the ring buffer and they use
    /// *interior mutability* to modify it.
    slots: UnsafeCell<[MaybeUninit<T>]>,
}
}

// SAFETY: If T can be moved between threads, RingBuffer can as well.
unsafe impl<T: Send> Send for RingBuffer<T> {}

impl<T> RingBuffer<T> {
    fn construct(capacity: usize) -> Box<Self> {
        Self::instantiate(capacity)
    }

    pub(super) fn capacity(&self) -> usize {
        self.slots.get().len()
    }

    pub(super) fn data_ptr(&self) -> *mut T {
        self.slots.get().cast()
    }
}

impl<T> Drop for RingBuffer<T> {
    /// Drops all non-empty slots.
    fn drop(&mut self) {
        // SAFETY: this is called exactly once, no references to any elements exist anymore.
        unsafe { self.drop_all_elements() };
        // The memory will be deallocated if and when the containing `Box` is dropped.
    }
}

/// A `RingBuffer` can be shared between threads.
///
/// `T` does not need to be `Sync`, because we never share it across threads.
/// For example, [`std::cell::Cell`] is `Send` but not `Sync`:
///
/// ```
/// fn assert_sync<X: Sync + ?Sized>() {}
/// assert_sync::<rtrb::dst_box::RingBuffer<std::cell::Cell<u8>>>();
/// ```
// SAFETY: RingBuffer is only mutated (using *interior mutablility*)
// via Producer/Consumer (which are !Sync), all other access can be shared.
unsafe impl<T> Sync for RingBuffer<T> {}

// NB: `Send` might be implemented by different storage backends,
// but it is not necessary for correct behavior of the RingBuffer.

impl<T> PartialEq for RingBuffer<T> {
    fn eq(&self, other: &Self) -> bool {
        core::ptr::eq(self, other)
    }
}

impl<T> Eq for RingBuffer<T> {}

impl<T> RingBuffer<T> {
    /// Creates a ring buffer with the given `capacity`.
    ///
    /// A (single) [`Producer`] for writing into the ring buffer can be created with
    /// [`RingBuffer::producer()`].
    /// A (single) [`Consumer`] for reading from the ring buffer can be created with
    /// [`RingBuffer::consumer()`].
    ///
    /// # Panics
    ///
    /// Panics if `capacity * size_of::<T>()` exceeds `isize::MAX` bytes or,
    /// when `T` is a zero-sized type, if `capacity` is larger than `usize::MAX / 2`.
    ///
    /// # Examples
    ///
    /// ```
    /// use rtrb::dst_box::RingBuffer;
    ///
    /// let rb = RingBuffer::<f32>::new(100);
    /// ```
    ///
    /// Specifying an explicit type
    /// with the [turbofish](https://turbo.fish/)
    /// is is only necessary if it cannot be deduced by the compiler.
    ///
    /// ```
    /// use rtrb::dst_box::RingBuffer;
    ///
    /// let rb = RingBuffer::new(100);
    /// let mut producer = rb.producer().unwrap();
    /// assert_eq!(producer.push(0.0f32), Ok(()));
    /// ```
    pub fn new(capacity: usize) -> Box<Self> {
        let capacity = Self::update_capacity(capacity);
        assert!(
            capacity.checked_mul(2).is_some(),
            "capacity exceeds usize::MAX / 2"
        );
        Self::construct(capacity)
    }

    /// Creates a [`Producer`] (if it doesn't exist yet) for writing into the `RingBuffer`.
    ///
    /// # Examples
    ///
    /// Only one producer and one consumer can exist at once,
    /// but once a producer has been dropped, a new one can be created:
    /// ```
    /// use rtrb::dst_box::RingBuffer;
    ///
    /// let rb = RingBuffer::new(64);
    /// let mut producer = rb.producer().unwrap();
    /// let mut consumer = rb.consumer().unwrap();
    /// assert!(rb.producer().is_none());
    /// assert_eq!(producer.push(10), Ok(()));
    /// drop(producer);
    /// assert!(!consumer.has_producer());
    /// assert!(!rb.has_producer());
    /// let mut producer = rb.producer().unwrap();
    /// assert!(consumer.has_producer());
    /// assert!(rb.has_producer());
    /// assert_eq!(producer.push(20), Ok(()));
    /// assert_eq!(consumer.pop(), Ok(10));
    /// assert_eq!(consumer.pop(), Ok(20));
    /// ```
    pub fn producer(&self) -> Option<Producer<'_, T>> {
        let old_flags = self.flags.fetch_or(HAS_PRODUCER, Ordering::SeqCst);
        if old_flags & HAS_PRODUCER == 0 {
            let head = self.head.load(Ordering::Relaxed);
            let tail = self.tail.load(Ordering::Relaxed);
            // SAFETY: There is no producer yet, `head` and `tail` are valid.
            Some(unsafe { Producer::new(self, head, tail) })
        } else {
            None
        }
    }

    /// Creates a [`Consumer`] (if it doesn't exist yet) for reading from the `RingBuffer`.
    ///
    /// # Examples
    ///
    /// Only one producer and one consumer can exist at once,
    /// but once a consumer has been dropped, a new one can be created:
    /// ```
    /// use rtrb::dst_box::RingBuffer;
    ///
    /// let rb = RingBuffer::new(64);
    /// let mut producer = rb.producer().unwrap();
    /// let mut consumer = rb.consumer().unwrap();
    /// assert!(rb.consumer().is_none());
    /// assert_eq!(producer.push(10), Ok(()));
    /// assert_eq!(producer.push(20), Ok(()));
    /// assert_eq!(consumer.pop(), Ok(10));
    /// drop(consumer);
    /// assert!(!producer.has_consumer());
    /// assert!(!rb.has_consumer());
    /// let mut consumer = rb.consumer().unwrap();
    /// assert!(producer.has_consumer());
    /// assert!(rb.has_consumer());
    /// assert_eq!(consumer.pop(), Ok(20));
    /// ```
    pub fn consumer(&self) -> Option<Consumer<'_, T>> {
        let old_flags = self.flags.fetch_or(HAS_CONSUMER, Ordering::SeqCst);
        if old_flags & HAS_CONSUMER == 0 {
            let head = self.head.load(Ordering::Relaxed);
            let tail = self.tail.load(Ordering::Relaxed);
            // SAFETY: There is no consumer yet, `head` and `tail` are valid.
            Some(unsafe { Consumer::new(self, head, tail) })
        } else {
            None
        }
    }

    /// Returns `true` if a [`Producer`] exists for this `RingBuffer`.
    ///
    /// If not, it can be created with [`producer()`](RingBuffer::producer).
    ///
    /// See also [`Consumer::has_producer()`].
    pub fn has_producer(&self) -> bool {
        self.flags.load(Ordering::SeqCst) & HAS_PRODUCER != 0
    }

    /// Returns `true` if a [`Consumer`] exists for this `RingBuffer`.
    ///
    /// If not, it can be created with [`consumer()`](RingBuffer::consumer).
    ///
    /// See also [`Producer::has_consumer()`].
    pub fn has_consumer(&self) -> bool {
        self.flags.load(Ordering::SeqCst) & HAS_CONSUMER != 0
    }

    /// Calculates memory layout using the given `capacity`.
    ///
    /// This can be used to allocate (e.g. with [`alloc::alloc::alloc()`])
    /// the right amount of properly aligned memory to be used with [`RingBuffer::new_at()`].
    /// It is *not* needed when using [`RingBuffer::new()`].
    pub fn layout(capacity: usize) -> Layout {
        let capacity = Self::update_capacity(capacity);
        Self::layout_helper(capacity)
    }

    /// Creates a new `RingBuffer` at the given memory address.
    ///
    /// To access an already existing `RingBuffer` at a given address,
    /// use [`RingBuffer::from_raw_parts()`].
    /// This can be used, for example, to communicate between two processes
    /// via shared memory.
    ///
    /// The created `RingBuffer` will not be dropped automatically!
    /// This means that if any `T`s remain in the buffer, they will be leaked
    /// (which is only relevant if `T` implements `Drop`).
    /// To avoid this, call [`std::ptr::drop_in_place()`],
    /// but make sure that no other reference exists at that point.
    ///
    /// If you don't need control over the memory location, you can simply use
    /// [`RingBuffer::new()`], which will automatically allocate the required memory
    /// on the heap.
    ///
    /// # Safety
    ///
    /// The provided memory must be uninitialized,
    /// must have the required size and alignment (see [`RingBuffer::layout()`]),
    /// it must exist at least as long as the returned reference
    /// and can only be accessed via the `&RingBuffer` returned from this method
    /// or from [`RingBuffer::from_raw_parts()`].
    pub unsafe fn new_at<'a>(ptr: *mut u8, capacity: usize) -> &'a Self {
        let capacity = Self::update_capacity(capacity);
        let ptr = Self::coerce(ptr, capacity);
        // SAFETY: Pointer is valid and no other reference exists.
        unsafe {
            Self::default_initialize(ptr);
        }
        // SAFETY: `ptr` is non-null and object is fully initialized.
        unsafe { &*ptr }
    }

    /// Provides access to an existing `RingBuffer` at a given memory address.
    ///
    /// [`RingBuffer::new_at()`] creates a `RingBuffer` at some
    /// (allocated but uninitialized) memory location.
    /// `RingBuffer::from_raw_parts()` provides access to an already
    /// existing `RingBuffer` at the given address. Both are extremely unsafe!
    ///
    /// # Safety
    ///
    /// The provided memory must have been initialized by [`RingBuffer::new_at()`]
    /// (using the same `capacity`)
    /// and the memory allocation must exist at least as long as the returned reference.
    /// There are no ABI stability guarantees.
    pub unsafe fn from_raw_parts<'a>(ptr: *mut u8, capacity: usize) -> &'a Self {
        let capacity = Self::update_capacity(capacity);
        let ptr = Self::coerce(ptr, capacity);
        // SAFETY: `ptr` must be non-null and object must be fully initialized.
        unsafe { &*ptr }
    }

    const fn update_capacity(capacity: usize) -> usize {
        // No need to update, we are not relying on power-of-two sizes.
        capacity
    }

    /// Drop all elements that are still in the buffer.
    ///
    /// After this, head and tail indices are invalid.
    ///
    /// # Safety
    ///
    /// This can only be called in the `Drop` implementation of the ring buffer.
    ///
    /// The threads must have been synchronized before via `self.flags`.
    #[inline(never)]
    unsafe fn drop_all_elements(&mut self) {
        // These atomic variables are *not* used for synchronizing the threads
        // before destruction.  Relaxed ordering is sufficient here.
        let mut head = self.head.load(Ordering::Relaxed);
        let tail = self.tail.load(Ordering::Relaxed);
        // Loop over all slots that hold a value and drop them.
        while head != tail {
            // SAFETY: All slots between head and tail have been initialized.
            unsafe { self.slot_ptr(head).drop_in_place() };
            head = self.increment1(head);
        }
    }

    pub(super) fn collapse_position(&self, pos: usize) -> usize {
        // Wraps from the range `0 .. 2 * capacity` to `0 .. capacity`.
        debug_assert!(pos == 0 || pos < 2 * self.capacity());
        if pos < self.capacity() {
            pos
        } else {
            pos - self.capacity()
        }
    }

    /// Returns a pointer to the (possibly uninitialized) slot at position `pos`.
    ///
    /// # Safety
    ///
    /// `pos` must be valid.
    ///
    /// If `pos == 0 && capacity == 0`, the returned pointer must not be dereferenced!
    pub(super) unsafe fn slot_ptr(&self, pos: usize) -> *mut T {
        // SAFETY: See docstring.
        unsafe { self.data_ptr().add(self.collapse_position(pos)) }
    }

    /// Increments a position by going `n` slots forward.
    pub(super) fn increment(&self, pos: usize, n: usize) -> usize {
        debug_assert!(pos == 0 || pos < 2 * self.capacity());
        debug_assert!(n <= self.capacity());
        let threshold = 2 * self.capacity() - n;
        if pos < threshold {
            pos + n
        } else {
            pos - threshold
        }
    }

    /// Increments a position by going one slot forward.
    ///
    /// This might be more efficient than self.increment(..., 1).
    pub(super) fn increment1(&self, pos: usize) -> usize {
        debug_assert_ne!(self.capacity(), 0);
        debug_assert!(pos < 2 * self.capacity());
        if pos < 2 * self.capacity() - 1 {
            pos + 1
        } else {
            0
        }
    }

    /// Returns the distance between two positions.
    pub(super) fn distance(&self, a: usize, b: usize) -> usize {
        debug_assert!(a == 0 || a < 2 * self.capacity());
        debug_assert!(b == 0 || b < 2 * self.capacity());
        if a <= b {
            b - a
        } else {
            2 * self.capacity() - a + b
        }
    }

    pub(super) fn head(&self) -> usize {
        self.head.load(Ordering::Acquire)
    }

    pub(super) unsafe fn set_head(&self, value: usize) {
        self.head.store(value, Ordering::Release);
    }

    pub(super) fn tail(&self) -> usize {
        self.tail.load(Ordering::Acquire)
    }

    pub(super) unsafe fn set_tail(&self, value: usize) {
        self.tail.store(value, Ordering::Release);
    }

    pub(super) fn drop_producer(&self) {
        let _ = self.flags.fetch_and(!HAS_PRODUCER, Ordering::SeqCst);
    }

    pub(super) fn drop_consumer(&self) {
        let _ = self.flags.fetch_and(!HAS_CONSUMER, Ordering::SeqCst);
    }
}
