// DO NOT EDIT THIS FILE!
// It has been auto-generated from `codegen/templates/src/ring_buffer.rs.jinja`
// using the configuration file `codegen/configs/dst_box.toml`.

use core::cell::UnsafeCell;
use core::mem::MaybeUninit;

use super::{HAS_CONSUMER, HAS_PRODUCER};
use crate::atomic::*;
// Padded indices to avoid false sharing.
use crate::CachePadded;

use super::{Consumer, Producer};

dst_ring_buffer_instantiation! {
/// A bounded single-producer single-consumer (SPSC) queue.
///
/// Elements can be written with a [`Producer`] and read with a [`Consumer`],
/// which can be obtained with ... TODO
///
/// *See also the [module-level documentation](crate::dst_box).*
#[derive(Debug)]
pub struct RingBuffer<T> {
    pub(super) head: CachePadded<AtomicUsize>,
    pub(super) tail: CachePadded<AtomicUsize>,
    pub(super) flags: AtomicU8,
    /// Storage for the ring buffer elements (dynamically sized).
    ///
    /// This must be in an `UnsafeCell` because both producer and consumer
    /// have a (non-mutable) reference to the ring buffer and they use
    /// *interior mutability* to modify it.
    slots: UnsafeCell<[MaybeUninit<T>]>,
}
}

// SAFETY: If T can be moved between threads, RingBuffer can as well.
unsafe impl<T: Send> Send for RingBuffer<T> {}

impl<T> RingBuffer<T> {
    fn construct(capacity: usize) -> Box<Self> {
        Self::instantiate(capacity)
    }

    pub(super) fn capacity(&self) -> usize {
        self.slots.get().len()
    }

    pub(super) fn data_ptr(&self) -> *mut T {
        self.slots.get().cast()
    }
}

impl<T> Drop for RingBuffer<T> {
    /// Drops all non-empty slots.
    fn drop(&mut self) {
        // SAFETY: this is called exactly once, no references to any elements exist anymore.
        unsafe { self.drop_all_elements() };
        // The memory will be deallocated if and when the containing `Box` is dropped.
    }
}

/// A `RingBuffer` can be shared between threads.
///
/// `T` does not need to be `Sync`, because we never share it across threads.
/// For example, [`std::cell::Cell`] is `Send` but not `Sync`:
///
/// ```
/// fn assert_sync<X: Sync + ?Sized>() {}
/// assert_sync::<rtrb::dst_box::RingBuffer<std::cell::Cell<u8>>>();
/// ```
// SAFETY: RingBuffer is only mutated (using *interior mutablility*)
// via Producer/Consumer (which are !Sync), all other access can be shared.
unsafe impl<T> Sync for RingBuffer<T> {}

// NB: `Send` might be implemented by different storage backends,
// but it is not necessary for correct behavior of the RingBuffer.

impl<T> PartialEq for RingBuffer<T> {
    fn eq(&self, other: &Self) -> bool {
        core::ptr::eq(self, other)
    }
}

impl<T> Eq for RingBuffer<T> {}

impl<T> RingBuffer<T> {
    /// Creates a ring buffer with the given `capacity`.
    ///
    /// A (single) [`Producer`] for writing into the ring buffer can be created with
    /// [`RingBuffer::producer()`].
    /// A (single) [`Consumer`] for reading from the ring buffer can be created with
    /// [`RingBuffer::consumer()`].
    ///
    /// # Examples
    ///
    /// ```
    /// use rtrb::dst_box::RingBuffer;
    ///
    /// let rb = RingBuffer::<f32>::new(100);
    /// ```
    ///
    /// Specifying an explicit type
    /// with the [turbofish](https://turbo.fish/)
    /// is is only necessary if it cannot be deduced by the compiler.
    ///
    /// ```
    /// use rtrb::dst_box::RingBuffer;
    ///
    /// let rb = RingBuffer::new(100);
    /// let mut producer = rb.producer().unwrap();
    /// assert_eq!(producer.push(0.0f32), Ok(()));
    /// ```
    pub fn new(capacity: usize) -> Box<Self> {
        // TODO: updating capacity will happen in construct()?
        let capacity = Self::update_capacity(capacity);
        Self::construct(capacity)
    }

    /// Creates a [`Producer`] (if it doesn't exist yet) for writing into the `RingBuffer`.
    ///
    /// # Examples
    ///
    /// Only one producer and one consumer can exist at once,
    /// but once a producer has been dropped, a new one can be created:
    /// ```
    /// use rtrb::dst_box::RingBuffer;
    ///
    /// let rb = RingBuffer::new(64);
    /// let mut producer = rb.producer().unwrap();
    /// let mut consumer = rb.consumer().unwrap();
    /// assert!(rb.producer().is_none());
    /// assert_eq!(producer.push(10), Ok(()));
    /// drop(producer);
    /// assert!(!consumer.has_producer());
    /// assert!(!rb.has_producer());
    /// let mut producer = rb.producer().unwrap();
    /// assert!(consumer.has_producer());
    /// assert!(rb.has_producer());
    /// assert_eq!(producer.push(20), Ok(()));
    /// assert_eq!(consumer.pop(), Ok(10));
    /// assert_eq!(consumer.pop(), Ok(20));
    /// ```
    pub fn producer(&self) -> Option<Producer<'_, T>> {
        use core::cell::Cell;
        let old_flags = self.flags.fetch_or(HAS_PRODUCER, Ordering::SeqCst);
        if old_flags & HAS_PRODUCER == 0 {
            let head = self.head.load(Ordering::Relaxed);
            let tail = self.tail.load(Ordering::Relaxed);
            Some(Producer {
                buffer: self,
                cached_head: Cell::new(head),
                cached_tail: Cell::new(tail),
            })
        } else {
            None
        }
    }

    /// Creates a [`Consumer`] (if it doesn't exist yet) for reading from the `RingBuffer`.
    ///
    /// # Examples
    ///
    /// Only one producer and one consumer can exist at once,
    /// but once a consumer has been dropped, a new one can be created:
    /// ```
    /// use rtrb::dst_box::RingBuffer;
    ///
    /// let rb = RingBuffer::new(64);
    /// let mut producer = rb.producer().unwrap();
    /// let mut consumer = rb.consumer().unwrap();
    /// assert!(rb.consumer().is_none());
    /// assert_eq!(producer.push(10), Ok(()));
    /// assert_eq!(producer.push(20), Ok(()));
    /// assert_eq!(consumer.pop(), Ok(10));
    /// drop(consumer);
    /// assert!(!producer.has_consumer());
    /// assert!(!rb.has_consumer());
    /// let mut consumer = rb.consumer().unwrap();
    /// assert!(producer.has_consumer());
    /// assert!(rb.has_consumer());
    /// assert_eq!(consumer.pop(), Ok(20));
    /// ```
    pub fn consumer(&self) -> Option<Consumer<'_, T>> {
        use core::cell::Cell;
        let old_flags = self.flags.fetch_or(HAS_CONSUMER, Ordering::SeqCst);
        if old_flags & HAS_CONSUMER == 0 {
            let head = self.head.load(Ordering::Relaxed);
            let tail = self.tail.load(Ordering::Relaxed);
            Some(Consumer {
                buffer: self,
                cached_head: Cell::new(head),
                cached_tail: Cell::new(tail),
            })
        } else {
            None
        }
    }

    /// Returns `true` if a [`Producer`] exists for this `RingBuffer`.
    ///
    /// If not, it can be created with [`producer()`](RingBuffer::producer).
    ///
    /// See also [`Consumer::has_producer()`].
    pub fn has_producer(&self) -> bool {
        self.flags.load(Ordering::SeqCst) & HAS_PRODUCER != 0
    }

    /// Returns `true` if a [`Consumer`] exists for this `RingBuffer`.
    ///
    /// If not, it can be created with [`consumer()`](RingBuffer::consumer).
    ///
    /// See also [`Producer::has_consumer()`].
    pub fn has_consumer(&self) -> bool {
        self.flags.load(Ordering::SeqCst) & HAS_CONSUMER != 0
    }

    const fn update_capacity(capacity: usize) -> usize {
        // No need to update, we are not relying on power-of-two sizes.
        capacity
    }

    /// Drop all elements that are still in the buffer.
    ///
    /// After this, head and tail indices are invalid.
    ///
    /// # Safety
    ///
    /// This can only be called in the `Drop` implementation of the ring buffer.
    ///
    /// The threads must have been synchronized before via `self.flags`.
    #[inline(never)]
    unsafe fn drop_all_elements(&mut self) {
        // These atomic variables are *not* used for synchronizing the threads
        // before destruction.  Relaxed ordering is sufficient here.
        let mut head = self.head.load(Ordering::Relaxed);
        let tail = self.tail.load(Ordering::Relaxed);
        // Loop over all slots that hold a value and drop them.
        while head != tail {
            // SAFETY: All slots between head and tail have been initialized.
            unsafe { self.slot_ptr(head).drop_in_place() };
            head = self.increment1(head);
        }
    }

    pub(super) fn collapse_position(&self, pos: usize) -> usize {
        // Wraps from the range `0 .. 2 * capacity` to `0 .. capacity`.
        debug_assert!(pos == 0 || pos < 2 * self.capacity());
        if pos < self.capacity() {
            pos
        } else {
            pos - self.capacity()
        }
    }

    /// Returns a pointer to the (possibly uninitialized) slot at position `pos`.
    ///
    /// # Safety
    ///
    /// `pos` must be valid.
    ///
    /// If `pos == 0 && capacity == 0`, the returned pointer must not be dereferenced!
    pub(super) unsafe fn slot_ptr(&self, pos: usize) -> *mut T {
        // SAFETY: See docstring.
        unsafe { self.data_ptr().add(self.collapse_position(pos)) }
    }

    /// Increments a position by going `n` slots forward.
    pub(super) fn increment(&self, pos: usize, n: usize) -> usize {
        debug_assert!(pos == 0 || pos < 2 * self.capacity());
        debug_assert!(n <= self.capacity());
        let threshold = 2 * self.capacity() - n;
        if pos < threshold {
            pos + n
        } else {
            pos - threshold
        }
    }

    /// Increments a position by going one slot forward.
    ///
    /// This might be more efficient than self.increment(..., 1).
    pub(super) fn increment1(&self, pos: usize) -> usize {
        debug_assert_ne!(self.capacity(), 0);
        debug_assert!(pos < 2 * self.capacity());
        if pos < 2 * self.capacity() - 1 {
            pos + 1
        } else {
            0
        }
    }

    /// Returns the distance between two positions.
    pub(super) fn distance(&self, a: usize, b: usize) -> usize {
        debug_assert!(a == 0 || a < 2 * self.capacity());
        debug_assert!(b == 0 || b < 2 * self.capacity());
        if a <= b {
            b - a
        } else {
            2 * self.capacity() - a + b
        }
    }
}
