{% include "definitions.jinja" %}
{# You are currently looking at the template, so you can ignore the following comment! #}
// Do not edit this file! It has been auto-generated from `codegen/templates/src/mod.rs`.
{# TODO: mention the config file used? #}

{{ module_docstring }}
{% if bip and not contiguous %}
compile_error!("bip implies contiguous");
{% endif %}
mod ring_buffer;
pub use ring_buffer::RingBuffer;
mod producer;
pub use producer::Producer;
mod consumer;
pub use consumer::Consumer;
{% if arc %}
mod arc_ring_buffer;
{% endif %}

pub mod chunks;

/// Error type for [`Consumer::peek()`].
#[doc(inline)]
pub use crate::PeekError;

/// Error type for [`Consumer::pop()`].
#[doc(inline)]
pub use crate::PopError;

/// Error type for [`Producer::push()`].
#[doc(inline)]
pub use crate::PushError;

/// Error type for [`Producer::write_chunk()`], [`Producer::write_chunk_uninit()`]
/// and [`Consumer::read_chunk()`].
///
/// To get the maximum number of available slots beforehand
/// (and therefore avoid this error), use
{% if bip %}
/// [`Producer::slots_contiguous_max()`] and [`Consumer::slots_contiguous_first()`],
{% else %}
/// [`Producer::slots()`] and [`Consumer::slots()`],
{% endif %}
/// respectively.
#[doc(inline)]
pub use crate::ChunkError;

/// Extension trait providing a [`copy_to_uninit()`](CopyToUninit::copy_to_uninit)
/// method on built-in slices.
///
/// This can be used to safely copy data to the
{% if contiguous %}
/// slice returned from [`WriteChunkUninit::as_mut_slice()`].
{% else %}
/// slices returned from [`WriteChunkUninit::as_mut_slices()`].
{% endif %}
///
/// To use this, the trait has to be brought into scope, e.g. with:
///
/// ```
/// use {{ module }}::CopyToUninit as _;
/// ```
///
/// TODO: update link:
///
/// For a usage example, see [`crate::chunks`](crate::chunks#common-access-patterns).
#[doc(inline)]
pub use crate::CopyToUninit;
