{% include "definitions.jinja" %}
{# You are currently looking at the template, so you can ignore the following comment! #}
// Do not edit this file! It has been auto-generated from `codegen/templates/src/mod.rs`.
{# TODO: mention the config file used? #}

{{ module_docstring -}}
//!
//! # Usage
//!
//! A [`RingBuffer`] consists of two parts:
//! a [`Producer`] for writing into the ring buffer and
//! a [`Consumer`] for reading from the ring buffer.
//!
//! TODO: more usage instructions
{% if storage != "vrb" %}
//!
//! # Examples
//!
//! Moving single elements into and out of a queue with
//! [`Producer::push()`] and [`Consumer::pop()`], respectively:
//!
//! ```
//! use {{ module_path }}::{RingBuffer, PushError, PopError};
//!
{{ doctest_create_ring_buffer(2, prefix="//!") }}
//!
//! assert_eq!(p.push(10), Ok(()));
//! assert_eq!(p.push(20), Ok(()));
//! assert_eq!(p.push(30), Err(PushError::Full(30)));
//!
//! std::thread::scope(|s| {
//!     s.spawn(move || {
//!         assert_eq!(c.pop(), Ok(10));
//!         assert_eq!(c.pop(), Ok(20));
//!         assert_eq!(c.pop(), Err(PopError::Empty));
//!     });
//! });
//! ```
//!
//! See the documentation of the [`chunks#examples`] module
//! for examples that write multiple items at once with
//! [`Producer::write_chunk_uninit()`] and [`Producer::write_chunk()`]
//! and read multiple items with [`Consumer::read_chunk()`].
{% endif %}

{% if arc %}
const IS_ABANDONED: u8 = 0b10000000;
{% else %}
const HAS_PRODUCER: u8 = 0b10000000;
const HAS_CONSUMER: u8 = 0b01000000;
{% endif %}

{% if bip and not contiguous %}
compile_error!("bip implies contiguous");
{% endif %}
mod ring_buffer;
pub use ring_buffer::RingBuffer;
mod producer;
pub use producer::Producer;
mod consumer;
pub use consumer::Consumer;
{% if arc %}
mod arc_ring_buffer;
{% endif %}

pub mod chunks;

// Only used in documentation:
#[allow(unused_imports)]
use chunks::WriteChunkUninit;

/// Error type for [`Consumer::peek()`].
#[doc(inline)]
pub use crate::PeekError;

/// Error type for [`Consumer::pop()`].
#[doc(inline)]
pub use crate::PopError;

/// Error type for [`Producer::push()`].
#[doc(inline)]
pub use crate::PushError;

/// Error type for [`Producer::write_chunk()`], [`Producer::write_chunk_uninit()`]
/// and [`Consumer::read_chunk()`].
///
/// To get the maximum number of available slots beforehand
/// (and therefore avoid this error), use
{% if bip %}
/// [`Producer::slots_contiguous_max()`] and [`Consumer::slots_contiguous_first()`],
{% else %}
/// [`Producer::slots()`] and [`Consumer::slots()`],
{% endif %}
/// respectively.
#[doc(inline)]
pub use crate::ChunkError;

/// Extension trait providing a [`copy_to_uninit()`](CopyToUninit::copy_to_uninit)
/// method on built-in slices.
///
/// This can be used to safely copy data to the
{% if contiguous %}
/// slice returned from [`WriteChunkUninit::as_mut_slice()`].
{% else %}
/// slices returned from [`WriteChunkUninit::as_mut_slices()`].
{% endif %}
///
/// To use this, the trait has to be brought into scope, e.g. with:
///
/// ```
/// use {{ module_path }}::CopyToUninit as _;
/// ```
///
/// TODO: update link:
///
/// For a usage example, see [`crate::chunks`](crate::chunks#common-access-patterns).
#[doc(inline)]
pub use crate::CopyToUninit;
