{% include "definitions.jinja" %}
{# You are currently looking at the template, so you can ignore the following comment! #}
// Do not edit this file! It has been auto-generated from `codegen/templates/src/mod.rs`.
{# TODO: mention the config file used? #}

{{ module_docstring }}

{% if storage == "array" %}
use core::cell::UnsafeCell;
use core::mem::MaybeUninit;
{% elif storage == "vec" %}
use alloc::vec::Vec;
use core::mem::ManuallyDrop;
{% endif %}

use crate::atomic::*;
{% if padded %}
// Padded indices to avoid false sharing.
use crate::CachePadded;
{% endif %}

/// A bounded single-producer single-consumer (SPSC) queue.
///
/// Elements can be written with a [`Producer`] and read with a [`Consumer`],
{% if arc %}
/// both of which can be obtained with [`RingBuffer::new()`].
{% else %}
/// which can be obtained with ... TODO
{% endif %}
///
/// *See also the [module-level documentation]({{ module }}).*
{% if storage == "array" %}
#[derive(Debug)]
pub struct RingBuffer<T, const N: usize> {
    head: {{ CachePadded("AtomicUsize") }},
    tail: {{ CachePadded("AtomicUsize") }},
    {% if bip %}
    // TODO: measure whether CachePadded helps
    skip: {{ CachePadded("AtomicUsize") }},
    {% endif %}
    flags: AtomicU8,
    /// The static array holding slots.
    ///
    /// This must be in an `UnsafeCell` because both producer and consumer
    /// have a (non-mutable) reference to the ring buffer and they use
    /// *interior mutability* to modify it.
    slots: UnsafeCell<[MaybeUninit<T>; N]>,
}

// SAFETY: If T can be moved between threads, RingBuffer can as well.
unsafe impl<T: Send, const N: usize> Send for RingBuffer<T, N> {}

impl<T, const N: usize> RingBuffer<T, N> {
    // Private helper function.
    const fn construct() -> Self {
        Self {
            head: {{ CachePadded_new("AtomicUsize::new(0)") }},
            tail: {{ CachePadded_new("AtomicUsize::new(0)") }},
            {% if bip %}
            skip: {{ CachePadded_new("AtomicUsize::new(0)") }},
            {% endif %}
            flags: AtomicU8::new(0),
            slots: UnsafeCell::new([const { MaybeUninit::uninit() }; N]),
        }
    }

    fn data_ptr(&self) -> *mut T {
        // TODO: what happens if N == 0?
        self.slots.get().cast()
    }

    fn capacity(&self) -> usize {
        N
    }
}

impl<T, const N: usize> Drop for RingBuffer<T, N> {
    fn drop(&mut self) {
        // SAFETY: this is called exactly once, no references to any elements exist anymore.
        unsafe { self.drop_all_elements() };
    }
}

{% if not arc %}
impl<T, const N: usize> Default for RingBuffer<T, N> {
    fn default() -> Self {
        Self::new()
    }
}
{% endif %}
{% elif storage == "dst" %}
compile_error!("TODO: dst");
{% elif storage == "vec" %}
#[derive(Debug)]
pub struct RingBuffer<T> {
    head: {{ CachePadded("AtomicUsize") }},
    tail: {{ CachePadded("AtomicUsize") }},
    {% if bip %}
    // TODO: measure whether CachePadded helps
    skip: {{ CachePadded("AtomicUsize") }},
    {% endif %}
    flags: AtomicU8,
    /// The buffer holding slots.
    data_ptr: *mut T,
    capacity: usize,
}

// SAFETY: If T can be moved between threads, RingBuffer can as well.
unsafe impl<T: Send> Send for RingBuffer<T> {}

impl<T> RingBuffer<T> {
    // Private helper function.
    fn construct(capacity: usize) -> Self {
        Self {
            head: {{ CachePadded_new("AtomicUsize::new(0)") }},
            tail: {{ CachePadded_new("AtomicUsize::new(0)") }},
            {% if bip %}
            skip: {{ CachePadded_new("AtomicUsize::new(0)") }},
            {% endif %}
            flags: AtomicU8::new(0),
            data_ptr: ManuallyDrop::new(Vec::with_capacity(capacity)).as_mut_ptr(),
            capacity,
        }
    }

    fn capacity(&self) -> usize {
        self.capacity
    }

    fn data_ptr(&self) -> *mut T {
        self.data_ptr
    }
}

impl<T> Drop for RingBuffer<T> {
    /// Drops all non-empty slots and deallocates the storage.
    fn drop(&mut self) {
        // SAFETY: this is called exactly once, no references to any elements exist anymore.
        unsafe { self.drop_all_elements() };

        // Finally, deallocate the buffer, but don't run any destructors.
        // SAFETY: data_ptr and capacity are still valid from the original initialization.
        unsafe { Vec::from_raw_parts(self.data_ptr, 0, self.capacity()) };
    }
}
{% elif storage == "vrb" %}
compile_error!("TODO: vrb");
{% else %}
compile_error!("Invalid storage = {{ storage }}");
{% endif %}

{% if not arc %}
impl<{{ params }}> RingBuffer<{{ args }}> {
    pub fn producer(&self) -> Option<Producer<{{ blank_lifetime }}>> {
    }
}
{% endif %}
