[package]
name = "rtrb"
version = "0.3.3"
authors = [
    "Stjepan Glavina <stjepang@gmail.com>",
    "Matthias Geier <Matthias.Geier@gmail.com>",
]
repository = "https://github.com/mgeier/rtrb"
description = "A realtime-safe single-producer single-consumer ring buffer"
readme = "README.md"
categories = ["concurrency", "data-structures", "no-std"]
keywords = ["lock-free", "wait-free", "spsc", "queue"]
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.79"

exclude = [
    ".*",
]

[workspace]
members = ["codegen"]
exclude = ["crossbeam", "performance-comparison"]

[features]
default = ["std"]
std = ["alloc"]
alloc = []
vrb = ["dep:libc", "alloc"]

[package.metadata.docs.rs]
all-features = true

[dependencies]
libc = { version = "0.2", optional = true }

[dev-dependencies]
rstest = "0.26.1"
rand = "0.10"
criterion = "0.8"
# TODO: This is only needed for the doctests of cache_padded.rs! Is there a way to avoid this?
crossbeam-utils = { version = "0.8", default-features = false }
crossbeam-queue-pr338 = { git = "https://github.com/mgeier/crossbeam", branch = "spsc", package = "crossbeam-queue" }
npnc = "0.2"
shared_memory = "0.12"

# aggressive optimization for benchmarks
[profile.bench]
lto = true
opt-level = 3
codegen-units = 1

[lib]
bench = false # Don't disturb criterion command line parsing

[[example]]
name = "quick"
required-features = ["alloc"]

[[bench]]
name = "single_thread_single_byte"
harness = false
# TODO: allow selecting different ring buffer variants (with different features)
required-features = ["alloc"]

[[bench]]
name = "single_thread_two_bytes"
harness = false
# TODO: allow selecting different ring buffer variants (with different features)
required-features = ["alloc"]

[[bench]]
name = "single_thread_with_chunks"
harness = false
# for Read/Write traits
required-features = ["std"]

[[bench]]
name = "two_threads"
harness = false
# Threads are only available in std
required-features = ["std"]

[[bench]]
name = "two_threads_with_chunks"
harness = false
# Threads are only available in std
required-features = ["std"]

[[bench]]
name = "two_threads_const"
harness = false
# Threads are only available in std
required-features = ["std"]

[[bench]]
name = "bip"
harness = false
# TODO: allow selecting different ring buffer variants (with different features)
required-features = ["alloc"]
