// Do not edit this file! It has been auto-generated from `codegen/templates/src/mod.rs`.
//! TODO: arc docs

/// A bounded single-producer single-consumer (SPSC) queue.
///
/// Elements can be written with a [`Producer`] and read with a [`Consumer`],
/// both of which can be obtained with [`RingBuffer::new()`].
///
/// *See also the [module-level documentation](rtrb::arc).*
pub struct RingBuffer<T> {
}

