// DO NOT EDIT THIS FILE!
// It has been auto-generated from `codegen/templates/src/producer.rs.jinja`
// using the configuration file `codegen/configs/arc.toml`.

use core::cell::Cell;

use super::arc_ring_buffer::ArcRingBuffer;
use super::IS_ABANDONED;
use super::{
    chunks::{WriteChunk, WriteChunkUninit},
    ChunkError, PushError, RingBuffer,
};
use crate::atomic::*;

// Only used in documentation:
#[allow(unused_imports)]
use super::Consumer;

/// The producer side of a [`RingBuffer`].
///
/// A `Producer` can be moved between threads,
/// but references from different threads are not allowed
/// (i.e. it is [`Send`] but not [`Sync`]).
///
/// Individual elements can be moved into the ring buffer with [`push()`](Producer::push),
/// multiple elements at once can be written with [`write_chunk()`](Producer::write_chunk)
/// and [`write_chunk_uninit()`](Producer::write_chunk_uninit).
///
/// The number of free slots currently available for writing can be obtained with
/// [`slots()`](Producer::slots).
///
/// A `Producer` can only be created with [`RingBuffer::new()`]
/// (together with its counterpart, the [`Consumer`]).
///
/// When the `Producer` is dropped, [`Consumer::is_abandoned()`] will return `true`.
/// This can be used as a crude way to communicate to the receiving thread
/// that no more data will be produced.
/// When the `Producer` is dropped after the [`Consumer`] has already been dropped,
/// all items remaining in the ring buffer will be dropped and the allocated memory
/// will be deallocated.
#[derive(Debug, PartialEq, Eq)]
pub struct Producer<T> {
    pub(super) buffer: ArcRingBuffer<T>,
    /// A copy of `buffer.head` for quick access.
    ///
    /// This value can be stale and sometimes needs to be resynchronized
    /// with `buffer.head`.
    pub(super) cached_head: Cell<usize>,
    /// A copy of `buffer.tail` for quick access.
    ///
    /// This value is always in sync with `buffer.tail`.
    pub(super) cached_tail: Cell<usize>,
}

/// It can be moved ...
/// ```
/// use rtrb::arc::Producer;
/// fn assert_send<X: Send>() {}
/// assert_send::<Producer<u8>>();
/// ```
/// ... but not shared between threads:
/// ```compile_fail
/// # use rtrb::arc::Producer;
/// fn assert_sync<X: Sync>() {}
/// assert_sync::<Producer<u8>>();
/// ```
// SAFETY: After moving a producer to another thread, there is still only a single thread
// that can access the producer side of the queue.
unsafe impl<T: Send> Send for Producer<T> where RingBuffer<T>: Sync {}

impl<T> Producer<T> {
    /// Attempts to push an element into the queue.
    ///
    /// The element is *moved* into the ring buffer and its slot
    /// is made available to be read by the [`Consumer`].
    ///
    /// # Errors
    ///
    /// If the queue is full, the element is returned back as an error.
    ///
    /// # Examples
    ///
    /// ```
    /// use rtrb::arc::{PushError, RingBuffer};
    ///
    /// let (mut producer, mut consumer) = RingBuffer::new(1);
    ///
    /// assert_eq!(producer.push(10), Ok(()));
    /// assert_eq!(producer.push(20), Err(PushError::Full(20)));
    /// ```
    pub fn push(&mut self, value: T) -> Result<(), PushError<T>> {
        if let Some(tail) = self.next_tail() {
            let b = &self.buffer;
            // SAFETY: tail points to an empty slot.
            unsafe { b.slot_ptr(tail).write(value) };
            let tail = b.increment1(tail);
            b.tail.store(tail, Ordering::Release);
            self.cached_tail.set(tail);
            Ok(())
        } else {
            Err(PushError::Full(value))
        }
    }

    /// Returns the number of slots available for writing.
    ///
    /// Since items can be concurrently consumed on another thread, the actual number
    /// of available slots may increase at any time
    /// (up to the [`capacity()`](Producer::capacity)).
    ///
    /// To check for a single available slot,
    /// using [`is_full()`](Producer::is_full) is often quicker
    /// (because it might not have to check an atomic variable).
    ///
    /// # Examples
    ///
    /// ```
    /// use rtrb::arc::RingBuffer;
    ///
    /// let (mut producer, mut consumer) = RingBuffer::new(4096);
    /// assert_eq!(producer.push(0.5f32), Ok(()));
    ///
    /// assert_eq!(producer.slots(), 4095);
    /// ```
    pub fn slots(&self) -> usize {
        let b = &self.buffer;
        let head = b.head.load(Ordering::Acquire);
        self.cached_head.set(head);
        b.capacity() - b.distance(head, self.cached_tail.get())
    }

    /// Returns `true` if there are currently no slots available for writing.
    ///
    /// A full ring buffer might cease to be full at any time
    /// if the corresponding [`Consumer`] is consuming items in another thread.
    ///
    /// # Examples
    ///
    /// ```
    /// use rtrb::arc::RingBuffer;
    ///
    /// let (mut producer, mut consumer) = RingBuffer::new(1);
    ///
    /// assert!(!producer.is_full());
    /// assert_eq!(producer.push(10), Ok(()));
    /// assert!(producer.is_full());
    /// ```
    ///
    /// Since items can be concurrently consumed on another thread, the ring buffer
    /// might not be full for long:
    ///
    /// ```
    /// # use rtrb::arc::RingBuffer;
    /// # let (mut producer, mut consumer) = RingBuffer::new(1);
    /// # assert_eq!(producer.push(10), Ok(()));
    /// if producer.is_full() {
    ///     // The buffer might be full, but it might as well not be
    ///     // if an item was just consumed on another thread.
    /// }
    /// ```
    ///
    /// However, if it's not full, another thread cannot change that:
    ///
    /// ```
    /// # use rtrb::arc::RingBuffer;
    /// # let (mut producer, mut consumer) = RingBuffer::new(1);
    /// # assert_eq!(producer.push(10), Ok(()));
    /// if !producer.is_full() {
    ///     // At least one slot is guaranteed to be available for writing.
    /// }
    /// ```
    pub fn is_full(&self) -> bool {
        self.next_tail().is_none()
    }

    /// Returns the total capacity of the queue.
    ///
    /// At any time, the capacity is subdivided into
    /// [`Producer::slots()`] available for writing and
    /// [`Consumer::slots()`] available for
    /// reading.
    ///
    /// # Examples
    ///
    /// ```
    /// use rtrb::arc::RingBuffer;
    ///
    /// let (mut producer, mut consumer) = RingBuffer::new(4096);
    ///
    /// assert_eq!(producer.push(-0.7), Ok(()));
    /// assert_eq!(producer.slots(), 4095);
    /// assert_eq!(consumer.slots(), 1);
    /// assert_eq!(producer.capacity(), 4096);
    /// assert_eq!(consumer.capacity(), 4096);
    /// ```
    pub fn capacity(&self) -> usize {
        self.buffer.capacity()
    }

    /// Returns `true` if the corresponding [`Consumer`] has been destroyed.
    ///
    /// TODO: update this note:
    ///
    /// Note that since Rust version 1.74.0, this is not synchronizing with the consumer thread
    /// anymore, see <https://github.com/mgeier/rtrb/issues/114>.
    /// In a future version of `rtrb`, the synchronizing behavior might be restored.
    ///
    /// # Examples
    ///
    /// ```
    /// use rtrb::arc::RingBuffer;
    ///
    /// let (mut producer, mut consumer) = RingBuffer::new(7);
    /// assert!(!producer.is_abandoned());
    /// assert_eq!(producer.push(10), Ok(()));
    /// drop(consumer);
    /// // The items that are still in the ring buffer are not accessible anymore.
    /// assert!(producer.is_abandoned());
    /// // Even though it's futile, items can still be written:
    /// assert_eq!(producer.push(11), Ok(()));
    /// ```
    ///
    /// Since the consumer can be concurrently dropped on another thread,
    /// the producer might become abandoned at any time:
    ///
    /// ```
    /// # use rtrb::arc::RingBuffer;
    /// # let (mut producer, mut consumer) = RingBuffer::new(1);
    /// # assert_eq!(producer.push(10), Ok(()));
    /// if !producer.is_abandoned() {
    ///     // Right now, the consumer might still be alive, but it might as well not be
    ///     // if another thread has just dropped it.
    /// }
    /// ```
    ///
    /// However, if it already is abandoned, it will stay that way:
    ///
    /// ```
    /// # use rtrb::arc::RingBuffer;
    /// # let (mut producer, mut consumer) = RingBuffer::new(1);
    /// # assert_eq!(producer.push(10), Ok(()));
    /// if producer.is_abandoned() {
    ///     // The consumer does definitely not exist anymore.
    /// }
    /// ```
    pub fn is_abandoned(&self) -> bool {
        self.buffer.flags.load(Ordering::Acquire) & IS_ABANDONED != 0
    }

    /// Get the tail position for writing the next slot, if available.
    ///
    /// This is a strict subset of the functionality implemented in `write_chunk_uninit()`.
    /// For performance, this special case is implemented separately.
    fn next_tail(&self) -> Option<usize> {
        let head = self.cached_head.get();
        let tail = self.cached_tail.get();
        let b = &self.buffer;
        // Check if the queue is *possibly* full.
        if b.distance(head, tail) == b.capacity() {
            // Refresh the head ...
            let head = b.head.load(Ordering::Acquire);
            self.cached_head.set(head);
            // ... and check if it's *really* full.
            if b.distance(head, tail) == b.capacity() {
                // `head` didn't change, the buffer is definitely full.
                return None;
            }
        }
        Some(tail)
    }

    /// Prepares a chunk of `n` slots (initially containing their [`Default`] value)
    /// for writing.
    ///
    /// [`WriteChunk::as_mut_slices()`]
    /// provides mutable access to the slots.
    /// After writing to those slots, they explicitly have to be made available
    /// to be read by the [`Consumer`] by calling [`WriteChunk::commit()`]
    /// or [`WriteChunk::commit_all()`].
    ///
    /// For an alternative that does not require the trait bound [`Default`],
    /// see [`Producer::write_chunk_uninit()`].
    ///
    /// If items are supposed to be moved from an iterator into the ring buffer,
    /// [`Producer::write_chunk_uninit()`] followed by [`WriteChunkUninit::fill_from_iter()`]
    /// can be used.
    ///
    /// # Errors
    ///
    /// If not enough slots are available, an error
    /// (containing the number of available slots) is returned.
    /// Use
    /// [`slots()`](Producer::slots)
    /// to obtain the number of available slots beforehand.
    ///
    /// # Examples
    ///
    /// See the documentation of the [`chunks`](crate::chunks#examples) module.
    pub fn write_chunk(&mut self, n: usize) -> Result<WriteChunk<'_, T>, ChunkError>
    where
        T: Default,
    {
        self.write_chunk_uninit(n).map(WriteChunk::from)
    }

    /// Prepares a chunk of `n` (uninitialized) slots for writing.
    ///
    /// [`WriteChunkUninit::as_mut_slices()`]
    /// provides mutable access
    /// to the uninitialized slots.
    /// After writing to those slots, they explicitly have to be made available
    /// to be read by the [`Consumer`] by calling [`WriteChunkUninit::commit()`]
    /// or [`WriteChunkUninit::commit_all()`].
    ///
    /// Alternatively, [`WriteChunkUninit::fill_from_iter()`] can be used
    /// to move items from an iterator into the available slots.
    /// All moved items are automatically made available to be read by the [`Consumer`].
    ///
    /// # Errors
    ///
    /// If not enough slots are available, an error
    /// (containing the number of available slots) is returned.
    /// Use
    /// [`slots()`](Producer::slots)
    /// to obtain the number of available slots beforehand.
    ///
    /// # Safety
    ///
    /// This function itself is safe, as is [`WriteChunkUninit::fill_from_iter()`].
    /// However, when using
    /// [`WriteChunkUninit::as_mut_slices()`],
    /// the user has to make sure that the relevant slots have been initialized
    /// before calling [`WriteChunkUninit::commit()`] or [`WriteChunkUninit::commit_all()`].
    ///
    /// For a safe alternative that provides
    /// mutable slices    /// of [`Default`]-initialized slots, see [`Producer::write_chunk()`].
    pub fn write_chunk_uninit(&mut self, n: usize) -> Result<WriteChunkUninit<'_, T>, ChunkError> {
        let head = self.cached_head.get();
        let tail = self.cached_tail.get();
        let b = &self.buffer;
        // Check if the queue has *possibly* not enough slots.
        if b.capacity() - b.distance(head, tail) < n {
            // Refresh the head ...
            let head = b.head.load(Ordering::Acquire);
            self.cached_head.set(head);
            // ... and check if there *really* are not enough slots.
            let slots = b.capacity() - b.distance(head, tail);
            if slots < n {
                return Err(ChunkError::TooFewSlots(slots));
            }
        }
        let offset = b.collapse_position(tail);
        // SAFETY: `offset` has been set to a valid position.
        Ok(unsafe { WriteChunkUninit::new(self, n, offset) })
    }
}
