// Do not edit this file! It has been auto-generated from `codegen/templates/src/consumer.rs`.

use core::cell::Cell;

use crate::atomic::*;
use super::{PopError, PeekError, RingBuffer, ChunkError, chunks::ReadChunk};
use super::{HAS_CONSUMER, HAS_PRODUCER};

// Only used in documentation:
#[allow(unused_imports)]
use super::Producer;

/// The consumer side of a [`RingBuffer`].
///
/// A `Consumer` can be moved between threads,
/// but references from different threads are not allowed
/// (i.e. it is [`Send`] but not [`Sync`]).
///
/// Individual elements can be moved out of the ring buffer with [`pop()`](Consumer::pop),
/// multiple elements at once can be read with [`read_chunk()`](Consumer::read_chunk).
///
/// The number of slots currently available for reading can be obtained with
/// [`slots()`](Consumer::slots).
///
/// A `Consumer` can only be created with [`RingBuffer::consumer()`].
#[derive(Debug, PartialEq, Eq)]
pub struct Consumer<'a, T, const N: usize> {
    pub(super) buffer: &'a RingBuffer<T, N>,
    pub(super) cached_head: Cell<usize>,
    pub(super) cached_tail: Cell<usize>,
}

impl<T, const N: usize> Drop for Consumer<'_, T, N> {
    fn drop(&mut self) {
        let _ = self.buffer.flags.fetch_and(!HAS_CONSUMER, Ordering::SeqCst);
    }
}

/// It can be moved ...
/// ```
/// use rtrb::embedded::Consumer;
/// fn assert_send<X: Send>() {}
/// assert_send::<Consumer<u8, 8>>();
/// ```
/// ... but not shared between threads:
/// ```compile_fail
/// # use rtrb::embedded::Consumer;
/// fn assert_sync<X: Sync>() {}
/// assert_sync::<Consumer<u8, 8>>();
/// ```
// SAFETY: After moving a consumer to another thread, there is still only a single thread
// that can access the consumer side of the queue.
unsafe impl<T: Send, const N: usize> Send for Consumer<'_, T, N>
where
    RingBuffer<T, N>: Sync
{}

impl<T, const N: usize> Consumer<'_, T, N> {
    /// Attempts to pop the next element from the queue.
    ///
    /// The element is *moved* out of the ring buffer and its slot
    /// is made available to be filled by the [`Producer`] again.
    ///
    /// # Errors
    ///
    /// If the queue is empty, an error is returned.
    ///
    /// # Examples
    ///
    /// ```
    /// use rtrb::embedded::{PopError, RingBuffer};
    ///
    /// let rb = RingBuffer::<_, 1>::new();
    /// let mut p = rb.producer().unwrap();
    /// let mut c = rb.consumer().unwrap();
    ///
    /// assert_eq!(p.push(10), Ok(()));
    /// assert_eq!(c.pop(), Ok(10));
    /// assert_eq!(c.pop(), Err(PopError::Empty));
    /// ```
    ///
    /// To obtain an [`Option<T>`](Option), use [`.ok()`](Result::ok) on the result.
    ///
    /// ```
    /// # use rtrb::embedded::RingBuffer;
    /// # let rb = RingBuffer::<_, 1>::new();
    /// # let mut p = rb.producer().unwrap();
    /// # let mut c = rb.consumer().unwrap();
    /// assert_eq!(p.push(20), Ok(()));
    /// assert_eq!(c.pop().ok(), Some(20));
    /// ```
    pub fn pop(&mut self) -> Result<T, PopError> {
        if let Some(head) = self.next_head() {
            let b = &self.buffer;
            // SAFETY: head points to an initialized slot.
            let value = unsafe { b.slot_ptr(head).read() };
            let head = b.increment1(head);
            b.head.store(head, Ordering::Release);
            self.cached_head.set(head);
            Ok(value)
        } else {
            Err(PopError::Empty)
        }
    }

    /// Attempts to get read access to the next element in the queue without removing it.
    ///
    /// # Errors
    ///
    /// If the queue is empty, an error is returned.
    ///
    /// # Examples
    ///
    /// ```
    /// use rtrb::embedded::{PeekError, RingBuffer};
    ///
    /// let rb = RingBuffer::<_, 1>::new();
    /// let mut p = rb.producer().unwrap();
    /// let mut c = rb.consumer().unwrap();
    ///
    /// assert_eq!(c.peek(), Err(PeekError::Empty));
    /// assert_eq!(p.push(10), Ok(()));
    /// assert_eq!(c.peek(), Ok(&10));
    /// assert_eq!(c.peek(), Ok(&10));
    /// ```
    pub fn peek(&self) -> Result<&T, PeekError> {
        if let Some(head) = self.next_head() {
            // SAFETY: head points to an initialized slot.
            Ok(unsafe { &*self.buffer.slot_ptr(head) })
        } else {
            Err(PeekError::Empty)
        }
    }

    /// Returns the number of slots available for reading.
    ///
    /// This number will also be reported via a [`ChunkError`] when calling
    /// [`read_chunk()`](Consumer::read_chunk) with a larger number.
    ///
    /// Since items can be concurrently produced on another thread, the actual number
    /// of available slots may increase at any time
    /// (up to the [`capacity()`](Consumer::capacity)).
    ///
    /// To check for a single available slot,
    /// using [`is_empty()`](Consumer::is_empty) is often quicker
    /// (because it might not have to check an atomic variable).
    ///
    ///
    /// # Examples
    ///
    /// ```
    /// use rtrb::embedded::RingBuffer;
    ///
    /// let rb = RingBuffer::<_, 1024>::new();
    /// let mut p = rb.producer().unwrap();
    /// let mut c = rb.consumer().unwrap();
    ///
    /// assert_eq!(c.slots(), 0);
    /// assert_eq!(p.push(0.0), Ok(()));
    /// assert_eq!(c.slots(), 1);
    /// ```
    pub fn slots(&self) -> usize {
        let b = &self.buffer;
        let tail = b.tail.load(Ordering::Acquire);
        self.cached_tail.set(tail);
        b.distance(self.cached_head.get(), tail)
    }


    /// Returns `true` if there are currently no slots available for reading.
    ///
    /// An empty ring buffer might cease to be empty at any time
    /// if the corresponding [`Producer`] is producing items in another thread.
    ///
    /// # Examples
    ///
    /// ```
    /// use rtrb::embedded::RingBuffer;
    ///
    /// let rb = RingBuffer::<_, 1>::new();
    /// let mut p = rb.producer().unwrap();
    /// let mut c = rb.consumer().unwrap();
    ///
    /// assert!(c.is_empty());
    /// assert_eq!(p.push(0.0), Ok(()));
    /// assert!(!c.is_empty());
    /// ```
    ///
    /// Since items can be concurrently produced on another thread, the ring buffer
    /// might not be empty for long:
    ///
    /// ```
    /// # use rtrb::embedded::RingBuffer;
    /// # let rb = RingBuffer::<_, 1>::new();
    /// # let mut p = rb.producer().unwrap();
    /// # let mut c = rb.consumer().unwrap();
    /// # assert_eq!(p.push(0.0), Ok(()));
    /// if c.is_empty() {
    ///     // The buffer might be empty, but it might as well not be
    ///     // if an item was just produced on another thread.
    /// }
    /// ```
    ///
    /// However, if it's not empty, another thread cannot change that:
    ///
    /// ```
    /// # use rtrb::embedded::RingBuffer;
    /// # let rb = RingBuffer::<_, 1>::new();
    /// # let mut p = rb.producer().unwrap();
    /// # let mut c = rb.consumer().unwrap();
    /// # assert_eq!(p.push(0.0), Ok(()));
    /// if !c.is_empty() {
    ///     // At least one slot is guaranteed to be available for reading.
    /// }
    /// ```
    pub fn is_empty(&self) -> bool {
        self.next_head().is_none()
    }

    /// Returns the total capacity of the queue.
    ///
    /// See [`Producer::capacity()`] for more information.
    pub fn capacity(&self) -> usize {
        self.buffer.capacity()
    }

    /// Returns `true` if the [`RingBuffer`] connected to this `Consumer`
    /// is also connected to a [`Producer`].
    ///
    /// This can change at any time when another thread creates or drops a `Producer`.
    ///
    /// See also [`RingBuffer::has_producer()`].
    pub fn has_producer(&self) -> bool {
        self.buffer.flags.load(Ordering::SeqCst) & HAS_PRODUCER != 0
    }


    /// Get the `head` position for reading the next slot, if available.
    ///
    /// This is a strict subset of the functionality implemented in `read_chunk()`.
    /// For performance, this special case is implemented separately.
    // TODO: check if using slots_contiguous_helper() is reasonably performant for bip
    fn next_head(&self) -> Option<usize> {
        let head = self.cached_head.get();
        let tail = self.cached_tail.get();

        // Check if the queue is *possibly* empty.
        if head == tail {
            // Refresh the tail ...
            let tail = self.buffer.tail.load(Ordering::Acquire);
            self.cached_tail.set(tail);
            // ... and check if it's *really* empty.
            if head == tail {
                // `tail` didn't change, queue is empty.
                return None;
            }
        }
        Some(head)
    }

    /// Prepares a chunk of `n` slots for reading.
    ///
    /// [`ReadChunk::as_slices()`]
    /// provides immutable access to the slots.
    /// After reading from those slots, they explicitly have to be made available
    /// to be written again by the [`Producer`] by calling [`ReadChunk::commit()`]
    /// or [`ReadChunk::commit_all()`].
    ///
    /// Alternatively, items can be moved out of the [`ReadChunk`] using iteration
    /// because it implements [`IntoIterator`]
    /// ([`ReadChunk::into_iter()`] can be used to explicitly turn it into an [`Iterator`]).
    /// All moved items are automatically made available to be written again by
    /// the [`Producer`].
    ///
    /// # Errors
    ///
    /// If not enough slots are available, an error
    /// (containing the number of available slots) is returned.
    /// Use
    /// [`slots()`](Consumer::slots)
    /// to obtain the number of available slots beforehand.
    ///
    /// # Examples
    ///
    /// See the documentation of the [`chunks`](super::chunks#examples) module.
    pub fn read_chunk(
        &mut self,
        n: usize,
    ) -> Result<ReadChunk<'_, T, N>, ChunkError> {
        let head = self.cached_head.get();
        let tail = self.cached_tail.get();
        let b = &self.buffer;
        // Check if the queue has *possibly* not enough slots.
        if b.distance(head, tail) < n {
            // Refresh the tail ...
            let tail = b.tail.load(Ordering::Acquire);
            self.cached_tail.set(tail);
            // ... and check if there *really* are not enough slots.
            let slots = b.distance(head, tail);
            if slots < n {
                return Err(ChunkError::TooFewSlots(slots));
            }
        }
        let offset = b.collapse_position(head);
        // SAFETY: `offset` has been set to a valid position.
        Ok(unsafe { ReadChunk::new(self, n, offset) })
    }
}