// DO NOT EDIT THIS FILE!
// It has been auto-generated from `codegen/templates/src/mod.rs.jinja`
// using the configuration file `codegen/configs/embedded.toml`.

//! TODO: does this make sense?
//!
//! no cache padding, no dynamic allocation
//!
//! So far, using power-of-two indices has not shown any performance advantages.
//! The compiler seems to make such optimizations automatically
//! when the capacity is known at compile time.
//!
//! instead of yet another configuration, could "cache padded" be a Cargo feature?
//!
//! what about cached indices? do they make sense in an embedded context?
//!
//! *See the [crate-level documentation](crate) for information about the available options.*
//!
//! # Usage
//!
//! A [`RingBuffer`] consists of two parts:
//! a [`Producer`] for writing into the ring buffer and
//! a [`Consumer`] for reading from the ring buffer.
//!
//! TODO: more usage instructions
//!
//! # Examples
//!
//! Moving single elements into and out of a queue with
//! [`Producer::push()`] and [`Consumer::pop()`], respectively:
//!
//! ```
//! use rtrb::embedded::{RingBuffer, PushError, PopError};
//!
//! let rb = RingBuffer::<_, 2>::new();
//! let mut producer = rb.producer().unwrap();
//! let mut consumer = rb.consumer().unwrap();
//!
//! assert_eq!(producer.push(10), Ok(()));
//! assert_eq!(producer.push(20), Ok(()));
//! assert_eq!(producer.push(30), Err(PushError::Full(30)));
//!
//! std::thread::scope(|s| {
//!     s.spawn(move || {
//!         assert_eq!(consumer.pop(), Ok(10));
//!         assert_eq!(consumer.pop(), Ok(20));
//!         assert_eq!(consumer.pop(), Err(PopError::Empty));
//!     });
//! });
//! ```
//!
//! See the documentation of the [`chunks#examples`] module
//! for examples that write/read multiple items at once.
//! See also:
//!
//!   * [`Producer::write_chunk()`]
//!   * [`Producer::write_chunk_uninit()`]
//!   * [`Producer::push_partial_slice()`] (if `T: Copy`)
//!   * [`Producer::push_entire_slice()`] (if `T: Copy`)
//!
//!   * [`Consumer::read_chunk()`]
//!   * [`Consumer::pop_partial_slice()`] (if `T: Copy`)
//!   * [`Consumer::pop_partial_slice_uninit()`] (if `T: Copy`)
//!   * [`Consumer::pop_entire_slice()`] (if `T: Copy`)
//!   * [`Consumer::pop_entire_slice_uninit()`] (if `T: Copy`)
//!
//! ## Usage with `static`
//!
//! A [`RingBuffer`] can be defined as a `static` item
//! ([`RingBuffer::new()`] is a `const` function to allow this usage):
//!
//! ```
//! use rtrb::embedded::{Consumer, Producer, RingBuffer};
//!
//! // This can be used either as a global variable or at function scope:
//! static RB: RingBuffer<i32, 64> = RingBuffer::new();
//!
//! // This can be called from any thread, and/or moved to any thread:
//! let mut producer = RB.producer().unwrap();
//! assert_eq!(producer.push(10), Ok(()));
//!
//! // It's possible to store producers/consumers in a lifetime-less `struct`,
//! // because they have `'static` lifetime:
//! struct MyStruct {
//!     consumer: Consumer<'static, i32>,
//! }
//! let mut s = MyStruct { consumer: RB.consumer().unwrap() };
//! assert_eq!(s.consumer.pop(), Ok(10));
//! ```

const HAS_PRODUCER: u8 = 0b10000000;
const HAS_CONSUMER: u8 = 0b01000000;

mod ring_buffer;
pub use ring_buffer::RingBuffer;
mod producer;
pub use producer::Producer;
mod consumer;
pub use consumer::Consumer;

pub mod chunks;

// Only used in documentation:
#[allow(unused_imports)]
use chunks::WriteChunkUninit;

/// Error type for [`Consumer::peek()`].
#[doc(inline)]
pub use crate::PeekError;

/// Error type for [`Consumer::pop()`].
#[doc(inline)]
pub use crate::PopError;

/// Error type for [`Producer::push()`].
#[doc(inline)]
pub use crate::PushError;

/// Error type for [`Producer::write_chunk()`], [`Producer::write_chunk_uninit()`]
/// and [`Consumer::read_chunk()`].
///
/// To get the maximum number of available slots beforehand
/// (and therefore avoid this error), use
/// [`Producer::slots()`] and [`Consumer::slots()`],
/// respectively.
#[doc(inline)]
pub use crate::ChunkError;

/// Extension trait providing a [`copy_to_uninit()`](CopyToUninit::copy_to_uninit)
/// method on built-in slices.
///
/// This can be used to safely copy data to the
/// slices returned from [`WriteChunkUninit::as_mut_slices()`].
///
/// To use this, the trait has to be brought into scope, e.g. with:
///
/// ```
/// use rtrb::embedded::CopyToUninit as _;
/// ```
///
/// TODO: update link:
///
/// For a usage example, see [`crate::chunks`](crate::chunks#common-access-patterns).
#[doc(inline)]
pub use crate::CopyToUninit;
