// DO NOT EDIT THIS FILE!
// It has been auto-generated from `codegen/templates/src/arc_ring_buffer.rs.jinja`
// using the configuration file `codegen/configs/bip_arc2.toml`.

use alloc::boxed::Box;
use core::ptr::NonNull;

use super::{Consumer, Producer, RingBuffer};

// Non-public helper type.
#[derive(Debug, PartialEq, Eq)]
pub(crate) struct ArcRingBuffer<T> {
    ptr: NonNull<RingBuffer<T>>,
}

// SAFETY: If RingBuffer is Send, ArcRingBuffer is as well.
unsafe impl<T> Send for ArcRingBuffer<T> where RingBuffer<T>: Send {}

impl<T> ArcRingBuffer<T> {
    // NB: this takes ownership of the RingBuffer, making sure that only one
    //     Producer and Consumer are ever created.
    #[allow(clippy::new_ret_no_self)]
    pub fn new(rb: Box<RingBuffer<T>>) -> (Producer<T>, Consumer<T>) {
        // NB: the following loads don't need Acquire (Relaxed would be enough),
        // but it's easier to reuse the helper functions.
        debug_assert!(!rb.is_abandoned());
        let head = rb.head();
        let tail = rb.tail();

        // We leak the `Box` here, but in the `Drop` implementation the pointer
        // will be turned back into a `Box` and its memory will be properly deallocated.
        let ptr = Box::leak(rb);
        // SAFETY: Pointer from `Box` is always non-null.
        let ptr = unsafe { NonNull::new_unchecked(ptr) };

        // SAFETY: `ptr` is valid, `head` and `tail` are correct.
        let p = unsafe { Producer::new(Self { ptr }, head, tail) };
        // SAFETY: `ptr` is valid, `head` and `tail` are correct.
        let c = unsafe { Consumer::new(Self { ptr }, head, tail) };
        (p, c)
    }
}

impl<T> Drop for ArcRingBuffer<T> {
    fn drop(&mut self) {
        // SAFETY: `ptr` is valid until we drop it. There are no mutable references.
        let we_have_to_clean_up = unsafe { self.ptr.as_ref().abandon() };
        if we_have_to_clean_up {
            // SAFETY: RingBuffer has been allocated with `Box::new()`.
            unsafe {
                drop_slow(self.ptr);
            }
        }
    }
}

/// Non-inlined part of `ArcRingBuffer::drop()`.
#[inline(never)]
unsafe fn drop_slow<T>(ptr: NonNull<RingBuffer<T>>) {
    // SAFETY: The caller of `ArcRingBuffer::from_ptr()` has to guarantee that the memory
    // has been allocated with `Box::new()` or compatible.
    unsafe {
        // Turn the pointer into a `Box` and immediately drop it, which deallocates the memory.
        drop(Box::from_raw(ptr.as_ptr()));
    }
}

impl<T> core::ops::Deref for ArcRingBuffer<T> {
    type Target = RingBuffer<T>;

    fn deref(&self) -> &Self::Target {
        // SAFETY: There are never any mutable references.
        unsafe { self.ptr.as_ref() }
    }
}
