// DO NOT EDIT THIS FILE!
// It has been auto-generated from `codegen/templates/src/mod.rs.jinja`
// using the configuration file `codegen/configs/bip_arc2.toml`.

//! A bi-partite ring buffer whose capacity is a power of two.
//!
//! If you need arbitrary capacities, use [`rtrb::bip_arc`](crate::bip_arc) instead.
//!
//! *See the [crate-level documentation](crate) for information about the available options.*
//!
//! # Usage
//!
//! In this module, the [`RingBuffer`] itself is not directly accessible.
//! Instead, [`RingBuffer::new()`] returns a [`Producer`] for writing into the ring buffer and
//! a [`Consumer`] for reading from the ring buffer.
//! As soon as both of these are dropped,
//! the underlying [`RingBuffer`] is automatically dropped as well.
//!
//! # Examples
//!
//! Moving single elements into and out of a queue with
//! [`Producer::push()`] and [`Consumer::pop()`], respectively:
//!
//! ```
//! use rtrb::bip_arc2::{RingBuffer, PushError, PopError};
//!
//! let (mut producer, mut consumer) = RingBuffer::new(2);
//!
//! assert_eq!(producer.push(10), Ok(()));
//! assert_eq!(producer.push(20), Ok(()));
//! assert_eq!(producer.push(30), Err(PushError::Full(30)));
//!
//! std::thread::scope(|s| {
//!     s.spawn(move || {
//!         assert_eq!(consumer.pop(), Ok(10));
//!         assert_eq!(consumer.pop(), Ok(20));
//!         assert_eq!(consumer.pop(), Err(PopError::Empty));
//!     });
//! });
//! ```
//!
//! See the documentation of the [`chunks#examples`] module
//! for examples that write/read multiple items at once.
//! See also:
//!
//!   * [`Producer::write_chunk()`]
//!   * [`Producer::write_chunk_uninit()`]
//!   * [`Producer::push_partial_slice()`] (if `T: Copy`)
//!   * [`Producer::push_entire_slice()`] (if `T: Copy`)
//!
//!   * [`Consumer::read_chunk()`]
//!   * [`Consumer::pop_partial_slice()`] (if `T: Copy`)
//!   * [`Consumer::pop_partial_slice_uninit()`] (if `T: Copy`)
//!   * [`Consumer::pop_entire_slice()`] (if `T: Copy`)
//!   * [`Consumer::pop_entire_slice_uninit()`] (if `T: Copy`)

const IS_ABANDONED: u8 = 0b10000000;

mod ring_buffer;
pub use ring_buffer::RingBuffer;
mod producer;
pub use producer::Producer;
mod consumer;
pub use consumer::Consumer;
mod arc_ring_buffer;

pub mod chunks;

// Only used in documentation:
#[allow(unused_imports)]
use chunks::WriteChunkUninit;

/// Error type for [`Consumer::peek()`].
#[doc(inline)]
pub use crate::PeekError;

/// Error type for [`Consumer::pop()`].
#[doc(inline)]
pub use crate::PopError;

/// Error type for [`Producer::push()`].
#[doc(inline)]
pub use crate::PushError;

/// Error type for [`Producer::write_chunk()`], [`Producer::write_chunk_uninit()`]
/// and [`Consumer::read_chunk()`].
///
/// To get the maximum number of available slots beforehand
/// (and therefore avoid this error), use
/// [`Producer::slots_contiguous_max()`] and [`Consumer::slots_contiguous_first()`],
/// respectively.
#[doc(inline)]
pub use crate::ChunkError;

/// Extension trait providing a [`copy_to_uninit()`](CopyToUninit::copy_to_uninit)
/// method on built-in slices.
///
/// This can be used to safely copy data to the
/// slice returned from [`WriteChunkUninit::as_mut_slice()`].
///
/// To use this, the trait has to be brought into scope, e.g. with:
///
/// ```
/// use rtrb::bip_arc2::CopyToUninit as _;
/// ```
#[doc(inline)]
pub use crate::CopyToUninit;
