// Do not edit this file! It has been auto-generated from `codegen/templates/src/ring_buffer.rs.jinja`.

use alloc::vec::Vec;
use core::mem::ManuallyDrop;

use crate::atomic::*;
// Padded indices to avoid false sharing.
use crate::CachePadded;
use super::arc_ring_buffer::ArcRingBuffer;

use super::{Consumer, Producer};

/// A bounded single-producer single-consumer (SPSC) queue.
///
/// Elements can be written with a [`Producer`] and read with a [`Consumer`],
/// both of which can be obtained with [`RingBuffer::new()`].
///
/// *See also the [module-level documentation](crate::bip_arc2).*
#[derive(Debug)]
pub struct RingBuffer<T> {
    pub(super) head: CachePadded<AtomicUsize>,
    pub(super) tail: CachePadded<AtomicUsize>,
    // TODO: measure whether CachePadded helps
    pub(super) skip: CachePadded<AtomicUsize>,
    pub(super) flags: AtomicU8,
    /// The buffer holding slots.
    data_ptr: *mut T,
    capacity: usize,
}

// SAFETY: If T can be moved between threads, RingBuffer can as well.
unsafe impl<T: Send> Send for RingBuffer<T> {}

impl<T> RingBuffer<T> {
    // Private helper function.
    fn construct(capacity: usize) -> Self {
        Self {
            head: CachePadded::new(AtomicUsize::new(0)),
            tail: CachePadded::new(AtomicUsize::new(0)),
            skip: CachePadded::new(AtomicUsize::new(capacity)),
            flags: AtomicU8::new(0),
            data_ptr: ManuallyDrop::new(Vec::with_capacity(capacity)).as_mut_ptr(),
            capacity,
        }
    }

    pub(super) fn capacity(&self) -> usize {
        self.capacity
    }

    pub(super) fn data_ptr(&self) -> *mut T {
        self.data_ptr
    }
}

impl<T> Drop for RingBuffer<T> {
    /// Drops all non-empty slots and deallocates the storage.
    fn drop(&mut self) {
        // SAFETY: this is called exactly once, no references to any elements exist anymore.
        unsafe { self.drop_all_elements() };

        // Finally, deallocate the buffer, but don't run any destructors.
        // SAFETY: data_ptr and capacity are still valid from the original initialization.
        unsafe { Vec::from_raw_parts(self.data_ptr, 0, self.capacity()) };
    }
}

/// A `RingBuffer` can be shared between threads.
///
/// `T` does not need to be `Sync`, because we never share it across threads.
// SAFETY: RingBuffer is only mutated (using *interior mutablility*)
// via Producer/Consumer (which are !Sync), all other access can be shared.
unsafe impl<T: Send> Sync for RingBuffer<T> {}

// NB: `Send` might be implemented by different storage backends,
// but it is not necessary for correct behavior of the RingBuffer.

impl<T> PartialEq for RingBuffer<T> {
    fn eq(&self, other: &Self) -> bool {
        core::ptr::eq(self, other)
    }
}

impl<T> Eq for RingBuffer<T> {}

impl<T> RingBuffer<T> {
    /// Creates a ring buffer with at least the given `capacity`
    /// and returns [`Producer`] and [`Consumer`].
    ///
    /// If the `capacity` isn't already a power of two, it is rounded up to the next one.
    ///
    /// # Examples
    ///
    /// ```
    /// use rtrb::bip_arc2::RingBuffer;
    ///
    /// let (p, c) = RingBuffer::<f32>::new(100);
    /// ```
    ///
    /// Specifying an explicit type
    /// with the [turbofish](https://turbo.fish/)
    /// is is only necessary if it cannot be deduced by the compiler.
    ///
    /// ```
    /// use rtrb::bip_arc2::RingBuffer;
    ///
    /// let (mut p, c) = RingBuffer::new(100);
    /// assert_eq!(p.push(0.0f32), Ok(()));
    /// ```
    #[allow(clippy::new_ret_no_self)]
    pub fn new(capacity: usize) -> (Producer<T>, Consumer<T>) {
        let capacity = Self::update_capacity(capacity);
        ArcRingBuffer::new(Self::construct(capacity))
    }

    /// Drop all elements that are still in the buffer.
    ///
    /// After this, head and tail indices are invalid.
    ///
    /// # Safety
    ///
    /// This can only be called in the `Drop` implementation of the ring buffer.
    ///
    /// The threads must have been synchronized before via `self.flags`.
    #[inline(never)]
    unsafe fn drop_all_elements(&mut self) {
        // These atomic variables are *not* used for synchronizing the threads
        // before destruction.  Relaxed ordering is sufficient here.
        let mut head = self.head.load(Ordering::Relaxed);
        let tail = self.tail.load(Ordering::Relaxed);
        let skip = self.skip.load(Ordering::Relaxed);
        // Loop over all slots that hold a value and drop them.
        while head != tail {
            if self.collapse_position(head) == skip {
                head = self.increment(head, self.capacity() - skip);
            }
            // SAFETY: All slots between head and tail have been initialized.
            unsafe { self.slot_ptr(head).drop_in_place() };
            head = self.increment1(head);
        }
    }

    const fn update_capacity(capacity: usize) -> usize {
        capacity.next_power_of_two()
    }

    pub(super) fn collapse_position(&self, pos: usize) -> usize {
        // Wraps from any number to the range `0 .. capacity`.
        // TODO: is capacity 0 supported?
        pos & (self.capacity() - 1)
    }

    /// Returns a pointer to the (possibly uninitialized) slot at position `pos`.
    ///
    /// # Safety
    ///
    /// `pos` must be valid.
    ///
    /// If `pos == 0 && capacity == 0`, the returned pointer must not be dereferenced!
    pub(super) unsafe fn slot_ptr(&self, pos: usize) -> *mut T {
        // SAFETY: See docstring.
        unsafe { self.data_ptr().add(self.collapse_position(pos)) }
    }

    /// Increments a position by going `n` slots forward.
    pub(super) fn increment(&self, pos: usize, n: usize) -> usize {
        pos.wrapping_add(n)
    }

    /// Increments a position by going one slot forward.
    ///
    /// This might be more efficient than self.increment(..., 1).
    pub(super) fn increment1(&self, pos: usize) -> usize {
        pos.wrapping_add(1)
    }

    /// Returns the distance between two positions.
    pub(super) fn distance(&self, a: usize, b: usize) -> usize {
        b.wrapping_sub(a)
    }
}