arc = true
padded = true
pow2 = false
storage = "vec"

module_docstring = """
//! Storage on the heap with reference-counted producer and consumer.
//! Use this if you can't decide!
//!
//! TODO: for now, this uses `Vec` storage, but if it turns out to be performant enough,
//! it could be replaced by DST storage,
//! making a separate [`rtrb::dst_arc`](crate::dst_arc) variant obsolete.
"""
