arc = true
bip = true
padded = true
pow2 = false
storage = "dst"

module_docstring = """
//! TODO: This is for testing purposes.
//!
//! There should be no functional differences between this and [`rtrb::bip_arc`](crate::bip_arc).
//! If it turns out to have better preformance, it should replace that.
"""
