arc = false
bip = true
padded = true
pow2 = false
storage = "array"

module_docstring = """
//! Bi-partite, `array` storage.
//!
//! See [`rtrb::bip_arc`](crate::bip_arc) and [`rtrb::bip_slice`](crate::bip_slice)
//! for bi-partite ring buffers with dynamic storage.
"""
