arc = false
bip = true
padded = true
pow2 = false
storage = "array"

module_docstring = """
//! A bi-partite ring buffer with a compile-time capacity.
//!
//! See [`rtrb::bip_arc`](crate::bip_arc) for a bi-partite ring buffer with dynamic storage.
"""
