arc = true
bip = true
padded = true
pow2 = true
storage = "vec"

module_docstring = """
//! A bi-partite ring buffer whose capacity is a power of two.
//!
//! If you need arbitrary capacities, use [`rtrb::bip_arc`](crate::bip_arc) instead.
"""
