arc = true
bip = true
padded = true
pow2 = true
storage = "dst"

module_docstring = """
//! Same as [`rtrb::bip_arc`](crate::bip_arc), but with a capacity that is a power of two.
//!
//! If you need arbitrary capacities, use [`rtrb::bip_arc`](crate::bip_arc) instead.
"""
