arc = false
padded = false
pow2 = false
storage = "array"

module_docstring = """
//! TODO: does this make sense?
//!
//! no cache padding, no dynamic allocation
//!
//! So far, using power-of-two indices has not shown any performance advantages.
//! The compiler seems to make such optimizations automatically
//! when the capacity is known at compile time.
//!
//! instead of yet another configuration, could "cache padded" be a Cargo feature?
//!
//! what about cached indices? do they make sense in an embedded context?
"""
