arc = false
padded = true
pow2 = false
storage = "dst"

module_docstring = """
//! TODO: Is this useful?
//!
//! TODO: Rename to `rtrb::boxed`?
//!
//! In contrast to [`rtrb::arc`](crate::arc), this provides a [`RingBuffer`]
//! that is *not* automatically dropped when both its [`Producer`] and its [`Consumer`]
//! go out of scope.
"""
