arc = false
padded = true
pow2 = false
storage = "dst"

module_docstring = """
//! Storage on the heap or in user-provided memory.
//!
//! In contrast to [`rtrb::arc`](crate::arc), this provides a [`RingBuffer`]
//! that is *not* automatically dropped when both its [`Producer`] and its [`Consumer`]
//! go out of scope.
"""
