// DO NOT EDIT THIS FILE!
// It has been auto-generated from `codegen/templates/src/consumer.rs.jinja`
// using the configuration file `codegen/configs/bip_arc.toml`.

use core::cell::Cell;
use core::mem::MaybeUninit;

use super::arc_ring_buffer::ArcRingBuffer;
use super::{chunks::ReadChunk, ChunkError, CopyToUninit as _, PeekError, PopError, RingBuffer};

// Only used in documentation:
#[allow(unused_imports)]
use super::Producer;

/// The consumer side of a [`RingBuffer`].
///
/// A `Consumer` can be moved between threads,
/// but references from different threads are not allowed
/// (i.e. it is [`Send`] but not [`Sync`]).
///
/// Individual elements can be moved out of the ring buffer with [`Consumer::pop()`],
/// multiple elements at once can be read with [`Consumer::read_chunk()`],
/// [`Consumer::pop_partial_slice()`] and [`Consumer::pop_partial_slice_uninit()`].
///
/// The number of slots currently available for reading can be obtained with
/// [`Consumer::slots()`].
///
/// A `Consumer` can only be created with [`RingBuffer::new()`]
/// (together with its counterpart, the [`Producer`]).
///
/// When the `Consumer` is dropped, [`Producer::is_abandoned()`] will return `true`.
/// This can be used as a crude way to communicate to the sending thread
/// that no more data will be consumed.
/// When the `Consumer` is dropped after the [`Producer`] has already been dropped,
/// all items remaining in the ring buffer will be dropped and the allocated memory
/// will be deallocated.
#[derive(Debug, PartialEq, Eq)]
pub struct Consumer<T> {
    /// A reference to the ring buffer.
    buffer: ArcRingBuffer<T>,

    /// A copy of `buffer.head` for quick access.
    ///
    /// This value is always in sync with `buffer.head`.
    // NB: Caching the head seems to have little effect on Intel CPUs, but it seems to
    //     improve performance on AMD CPUs, see https://github.com/mgeier/rtrb/pull/132
    cached_head: Cell<usize>,

    /// A copy of `buffer.tail` for quick access.
    ///
    /// This value can be stale and sometimes needs to be resynchronized with `buffer.tail`.
    cached_tail: Cell<usize>,
}

/// It can be moved ...
/// ```
/// use rtrb::bip_arc::Consumer;
/// fn assert_send<X: Send>() {}
/// assert_send::<Consumer<u8>>();
/// ```
/// ... but not shared between threads:
/// ```compile_fail
/// # use rtrb::bip_arc::Consumer;
/// fn assert_sync<X: Sync>() {}
/// assert_sync::<Consumer<u8>>();
/// ```
// SAFETY: After moving the consumer to another thread, there is still only a single thread
// that can access the consumer side of the queue.
unsafe impl<T: Send> Send for Consumer<T> where RingBuffer<T>: Sync {}

impl<T> Consumer<T> {
    pub(super) unsafe fn new(buffer: ArcRingBuffer<T>, head: usize, tail: usize) -> Self {
        Self {
            buffer,
            cached_head: Cell::new(head),
            cached_tail: Cell::new(tail),
        }
    }
}

impl<T> Consumer<T> {
    /// Attempts to pop the next element from the queue.
    ///
    /// The element is *moved* out of the ring buffer and its slot
    /// is made available to be filled by the [`Producer`] again.
    ///
    /// # Errors
    ///
    /// If the queue is empty, an error is returned.
    ///
    /// # Examples
    ///
    /// ```
    /// use rtrb::bip_arc::{PopError, RingBuffer};
    ///
    /// let (mut producer, mut consumer) = RingBuffer::new(1);
    ///
    /// assert_eq!(producer.push(10), Ok(()));
    /// assert_eq!(consumer.pop(), Ok(10));
    /// assert_eq!(consumer.pop(), Err(PopError::Empty));
    /// ```
    ///
    /// To obtain an [`Option<T>`](Option), use [`.ok()`](Result::ok) on the result.
    ///
    /// ```
    /// # use rtrb::bip_arc::RingBuffer;
    /// # let (mut producer, mut consumer) = RingBuffer::new(1);
    /// assert_eq!(producer.push(20), Ok(()));
    /// assert_eq!(consumer.pop().ok(), Some(20));
    /// ```
    pub fn pop(&mut self) -> Result<T, PopError> {
        if let Some(head) = self.next_head() {
            let b = &self.buffer;
            // SAFETY: head points to an initialized slot.
            let value = unsafe { b.slot_ptr(head).read() };
            let head = b.increment1(head);
            // SAFETY: `head` has been calculated correctly.
            unsafe {
                b.set_head(head);
            }
            self.cached_head.set(head);
            Ok(value)
        } else {
            Err(PopError::Empty)
        }
    }

    /// Attempts to get read access to the next element in the queue without removing it.
    ///
    /// # Errors
    ///
    /// If the queue is empty, an error is returned.
    ///
    /// # Examples
    ///
    /// ```
    /// use rtrb::bip_arc::{PeekError, RingBuffer};
    ///
    /// let (mut producer, mut consumer) = RingBuffer::new(1);
    ///
    /// assert_eq!(consumer.peek(), Err(PeekError::Empty));
    /// assert_eq!(producer.push(10), Ok(()));
    /// assert_eq!(consumer.peek(), Ok(&10));
    /// assert_eq!(consumer.peek(), Ok(&10));
    /// ```
    ///
    /// Note that `peek()` takes a shared reference to `self`,
    /// which means that other methods that take `&self` can be called
    /// while the returned reference is still in use.
    /// However, calling methods that take `&mut self`
    /// (like [`Consumer::pop()`] and [`Consumer::read_chunk()`]) leads to a compiler error:
    ///
    /// ```compile_fail
    /// use rtrb::bip_arc::RingBuffer;
    ///
    /// let (mut producer, mut consumer) = RingBuffer::new(8);
    /// producer.push(10).unwrap();
    /// let shared_ref = consumer.peek().unwrap();
    /// let value = consumer.pop().unwrap();
    /// assert_eq!(shared_ref, &10);
    /// ```
    pub fn peek(&self) -> Result<&T, PeekError> {
        if let Some(head) = self.next_head() {
            // SAFETY: head points to an initialized slot.
            Ok(unsafe { &*self.buffer.slot_ptr(head) })
        } else {
            Err(PeekError::Empty)
        }
    }

    /// Returns the number of slots available for reading.
    ///
    /// Since items can be concurrently produced on another thread, the actual number
    /// of available slots may increase at any time (up to the [`Consumer::capacity()`]).
    ///
    /// To check for a single available slot,
    /// using [`Consumer::is_empty()`] is often quicker
    /// (because it might not have to check an atomic variable).
    ///
    /// Due to wrap-around of the internal buffer, the reported slots might not be
    /// on a contiguous segment and therefore not entirely available for reading with
    /// [`read_chunk()`](Consumer::read_chunk). To get the number of contiguous slots,
    /// [`slots_contiguous_first()`](Consumer::slots_contiguous_first) can be used.
    ///
    /// # Examples
    ///
    /// ```
    /// use rtrb::bip_arc::RingBuffer;
    ///
    /// let (mut producer, mut consumer) = RingBuffer::new(1024);
    ///
    /// assert_eq!(consumer.slots(), 0);
    /// assert_eq!(producer.push(0.0), Ok(()));
    /// assert_eq!(consumer.slots(), 1);
    /// ```
    pub fn slots(&self) -> usize {
        let (one, two) = self.slots_contiguous();
        one + two
    }

    /// Returns the number of cached slots.
    ///
    /// In many cases, this will not provide all available slots,
    /// but it might be marginally faster than [`Consumer::slots()`]
    /// because it doesn't access the atomic write index.
    pub fn cached_slots(&self) -> usize {
        let b = &self.buffer;
        let head = self.cached_head.get();
        let collapsed_head = b.collapse_position(head);
        let tail = self.cached_tail.get();
        let collapsed_tail = b.collapse_position(tail);
        let is_empty = head == tail;
        if !is_empty && collapsed_tail <= collapsed_head {
            // NB: `skip` is only relevant if (collapsed) `tail < head`
            //     (or if the buffer is full).

            // `tail` has been refreshed since it last wrapped (even if `cached_tail` is outdated),
            // therefore `skip` needs no synchronization.
            // TODO: cache skip?
            b.skip() - collapsed_head
        } else {
            collapsed_tail - collapsed_head
        }
    }

    /// Returns size of first contiguous chunk and
    /// the refreshed `tail` (if it has already been refreshed) and
    /// `true` if there may be another chunk at the beginning of the buffer.
    #[inline]
    fn slots_contiguous_helper(&self) -> (usize, Option<usize>, bool) {
        let b = &self.buffer;
        let mut head = self.cached_head.get();
        let mut collapsed_head = b.collapse_position(head);
        let mut tail = self.cached_tail.get();
        let mut collapsed_tail = b.collapse_position(tail);

        macro_rules! reset_skip {
            () => {
                // SAFETY: There are no readable slots before `skip`.
                unsafe {
                    // `skip` is never read in the producer thread, only written. Storing it before
                    // `head` makes sure that we don't overwrite the producer's value prematurely.
                    b.set_skip(b.capacity());
                }
                head = b.increment(head, b.capacity() - collapsed_head);
                // SAFETY: We have read everything before `skip` and can skip the remaining slots.
                unsafe {
                    // Using `Release` here makes sure that storing `skip` "happens before".
                    b.set_head(head);
                }
                self.cached_head.set(head);
                collapsed_head = b.collapse_position(head);
                debug_assert_eq!(collapsed_head, 0);
            };
        }

        macro_rules! refresh_tail {
            () => {
                tail = b.tail();
                self.cached_tail.set(tail);
                collapsed_tail = b.collapse_position(tail);
            };
        }

        let mut is_empty = head == tail;
        if !is_empty && collapsed_tail <= collapsed_head {
            // NB: `skip` is only relevant if (collapsed) `tail < head`
            //     (or if the buffer is full).

            // `tail` has been refreshed since it last wrapped (even if `cached_tail` is outdated),
            // therefore `skip` needs no synchronization.
            let slots = b.skip() - collapsed_head;
            if slots > 0 {
                (slots, None, true)
            } else {
                reset_skip!();
                // `tail` will not wrap around, but it might reveal a few more slots.
                refresh_tail!();
                (collapsed_tail, Some(tail), false)
            }
        } else {
            // `tail` might wrap around.
            refresh_tail!();
            is_empty = head == tail;
            if !is_empty && collapsed_tail <= collapsed_head {
                // Loading `skip` "happens after" loading `tail`.
                let slots = b.skip() - collapsed_head;
                if slots > 0 {
                    (slots, Some(tail), true)
                } else {
                    reset_skip!();
                    (collapsed_tail, Some(tail), false)
                }
            } else {
                (collapsed_tail - collapsed_head, Some(tail), false)
            }
        }
    }

    /// Returns the number of slots of the next two contiguous segments available
    /// for reading with [`read_chunk()`](Consumer::read_chunk).
    ///
    /// In many cases, the second number will be `0`, but whenever the internal buffer
    /// wraps around, two contiguous segments might be available for reading.
    /// If the first number is `0`, the second will be `0` as well.
    ///
    /// The sum of both numbers is returned by [`slots()`](Consumer::slots).
    ///
    /// If you are only interested in the first number, using
    /// [`slots_contiguous_first()`](Consumer::slots_contiguous_first)
    /// should be slightly more efficient.
    ///
    /// The first number will also be reported via a [`ChunkError`] when calling
    /// [`read_chunk()`](Consumer::read_chunk) with a larger number.
    ///
    /// Since items can be concurrently produced on another thread, the actual number
    /// of available slots may increase at any time
    /// (up to a certain maximum that depends on the current read index and
    /// whether and how many slots have been skipped using
    /// [`Producer::write_chunk()`] or [`Producer::write_chunk_uninit()`],
    /// but at most up to the [`capacity()`](Consumer::capacity)).
    pub fn slots_contiguous(&self) -> (usize, usize) {
        let (slots, refreshed_tail, try_at_beginning) = self.slots_contiguous_helper();
        if !try_at_beginning {
            return (slots, 0);
        }
        let b = &self.buffer;
        let refreshed_tail = refreshed_tail.unwrap_or_else(|| {
            let tail = b.tail();
            self.cached_tail.set(tail);
            tail
        });
        (slots, b.collapse_position(refreshed_tail))
    }

    /// Returns the number of slots of the next contiguous segment available for reading with
    /// [`read_chunk()`](Consumer::read_chunk).
    ///
    /// This is the same as the first number returned by
    /// [`slots_contiguous()`](Consumer::slots_contiguous), but slightly more efficient.
    pub fn slots_contiguous_first(&self) -> usize {
        self.slots_contiguous_helper().0
    }

    /// Returns `true` if there are currently no slots available for reading.
    ///
    /// An empty ring buffer might cease to be empty at any time
    /// if the corresponding [`Producer`] is producing items in another thread.
    ///
    /// # Examples
    ///
    /// ```
    /// use rtrb::bip_arc::RingBuffer;
    ///
    /// let (mut producer, mut consumer) = RingBuffer::new(1);
    ///
    /// assert!(consumer.is_empty());
    /// assert_eq!(producer.push(0.0), Ok(()));
    /// assert!(!consumer.is_empty());
    /// ```
    ///
    /// Since items can be concurrently produced on another thread, the ring buffer
    /// might not be empty for long:
    ///
    /// ```
    /// # use rtrb::bip_arc::RingBuffer;
    /// # let (mut producer, mut consumer) = RingBuffer::new(1);
    /// # assert_eq!(producer.push(0.0), Ok(()));
    /// if consumer.is_empty() {
    ///     // The buffer might be empty, but it might as well not be
    ///     // if an item was just produced on another thread.
    /// }
    /// ```
    ///
    /// However, if it's not empty, another thread cannot change that:
    ///
    /// ```
    /// # use rtrb::bip_arc::RingBuffer;
    /// # let (mut producer, mut consumer) = RingBuffer::new(1);
    /// # assert_eq!(producer.push(0.0), Ok(()));
    /// if !consumer.is_empty() {
    ///     // At least one slot is guaranteed to be available for reading.
    /// }
    /// ```
    pub fn is_empty(&self) -> bool {
        self.next_head().is_none()
    }

    /// Returns the total capacity of the queue.
    ///
    /// See [`Producer::capacity()`] for more information.
    pub fn capacity(&self) -> usize {
        self.buffer.capacity()
    }

    /// Returns `true` if the corresponding [`Producer`] has been destroyed.
    ///
    /// Note that since Rust version 1.74.0 and before `rtrb` version 0.4,
    /// this was not synchronizing with the producer thread anymore,
    /// see [issue #114](https://github.com/mgeier/rtrb/issues/114).
    /// In `rtrb` version 0.4, the synchronizing behavior has been restored.
    ///
    /// # Examples
    ///
    /// ```
    /// use rtrb::bip_arc::RingBuffer;
    ///
    /// let (mut producer, mut consumer) = RingBuffer::new(7);
    /// assert!(!consumer.is_abandoned());
    /// assert_eq!(producer.push(10), Ok(()));
    /// drop(producer);
    /// assert!(consumer.is_abandoned());
    /// // The items that are left in the ring buffer can still be consumed:
    /// assert_eq!(consumer.pop(), Ok(10));
    /// ```
    ///
    /// Since the producer can be concurrently dropped on another thread,
    /// the consumer might become abandoned at any time:
    ///
    /// ```
    /// # use rtrb::bip_arc::RingBuffer;
    /// # let (mut producer, mut consumer) = RingBuffer::new(1);
    /// # assert_eq!(producer.push(10), Ok(()));
    /// if !consumer.is_abandoned() {
    ///     // Right now, the producer might still be alive, but it might as well not be
    ///     // if another thread has just dropped it.
    /// }
    /// ```
    ///
    /// However, if it already is abandoned, it will stay that way:
    ///
    /// ```
    /// # use rtrb::bip_arc::RingBuffer;
    /// # let (mut producer, mut consumer) = RingBuffer::new(1);
    /// # assert_eq!(producer.push(10), Ok(()));
    /// if consumer.is_abandoned() {
    ///     // The producer does definitely not exist anymore.
    /// }
    /// ```
    pub fn is_abandoned(&self) -> bool {
        self.buffer.is_abandoned()
    }

    /// Returns a read-only reference to the ring buffer.
    pub(super) fn buffer(&self) -> &RingBuffer<T> {
        &self.buffer
    }

    /// Get the `head` position for reading the next slot, if available.
    fn next_head(&self) -> Option<usize> {
        let (slots, _, _) = self.slots_contiguous_helper();
        if slots == 0 {
            None
        } else {
            Some(self.cached_head.get())
        }
    }

    /// Prepares a chunk of `n` slots for reading.
    ///
    /// [`ReadChunk::as_slice()`]
    /// provides immutable access to the slots.
    /// After reading from those slots, they explicitly have to be made available
    /// to be written again by the [`Producer`] by calling [`ReadChunk::commit()`]
    /// or [`ReadChunk::commit_all()`].
    ///
    /// Alternatively, items can be moved out of the [`ReadChunk`] using iteration
    /// because it implements [`IntoIterator`]
    /// ([`ReadChunk::into_iter()`] can be used to explicitly turn it into an [`Iterator`]).
    /// All moved items are automatically made available to be written again by the [`Producer`].
    ///
    /// # Errors
    ///
    /// If not enough slots are available, an error
    /// (containing the number of available slots) is returned.
    /// Use
    /// [`Consumer::slots_contiguous_first()`]
    /// to obtain the number of available slots beforehand.
    ///
    /// # Examples
    ///
    /// See the documentation of the [`chunks`](super::chunks#examples) module.
    pub fn read_chunk(&mut self, n: usize) -> Result<ReadChunk<'_, T>, ChunkError> {
        let b = &self.buffer;
        let (slots, _, _) = self.slots_contiguous_helper();
        if slots >= n {
            let offset = b.collapse_position(self.cached_head.get());
            // SAFETY: `offset` has been set to a valid position.
            Ok(unsafe { ReadChunk::new(self, n, offset) })
        } else {
            Err(ChunkError::TooFewSlots(slots))
        }
    }

    pub(super) unsafe fn advance(&self, n: usize) {
        let head = self.buffer.increment(self.cached_head.get(), n);
        // SAFETY: The user must make sure that `n` slots have been read.
        unsafe {
            self.buffer.set_head(head);
        }
        self.cached_head.set(head);
    }

    /// Copies as many items as possible from the ring buffer to the given `slice`.
    ///
    /// The copied slots are automatically made available to be written again by the [`Producer`].
    ///
    /// Returns two sub-slices of `slice`:
    /// - The part that has been filled with data from the ring buffer (possibly empty).
    /// - The unused remainder (possibly empty).
    ///
    /// To copy an entire slice (and fail otherwise), [`Consumer::pop_entire_slice()`] can be used.
    /// To copy into an uninitialized slice, [`Consumer::pop_partial_slice_uninit()`] can be used.
    ///
    /// # Examples
    ///
    /// ```
    /// use rtrb::Consumer;
    ///
    /// fn pop_at_least_one_element<'a>(
    ///     c: &mut Consumer<i32>,
    ///     s: &'a mut [i32],
    /// ) -> Result<&'a mut [i32], &'a mut [i32]> {
    ///     match c.pop_partial_slice(s) {
    ///         ([], remainder) => Err(remainder),
    ///         (_, remainder) => Ok(remainder),
    ///     }
    /// }
    ///
    /// fn block_while_popping_entire_slice(c: &mut Consumer<i32>, mut s: &mut [i32]) {
    ///     while let (_, remainder @ [_, ..]) = c.pop_partial_slice(s) {
    ///         std::thread::yield_now();
    ///         s = remainder;
    ///     }
    /// }
    /// ```
    ///
    /// For more examples, see the documentation of the [`chunks`](crate::chunks#examples) module.
    #[must_use]
    pub fn pop_partial_slice<'a>(&mut self, slice: &'a mut [T]) -> (&'a mut [T], &'a mut [T])
    where
        T: Copy,
    {
        // SAFETY: Transmuting &mut [T] to &mut [MaybeUninit<T>] is generally unsafe!
        // However, since we can guarantee that only valid T values will ever be written,
        // and the reference never leaves our control, it should be fine.
        let (popped, remainder) =
            unsafe { self.pop_partial_slice_uninit(&mut *(slice as *mut [_] as *mut _)) };
        // NB: This can be replaced by `assume_init_mut()` once stabilized:
        // SAFETY: `remainder` is a subslice of the original initialized buffer.
        (popped, unsafe { &mut *(remainder as *mut _ as *mut [_]) })
    }

    /// Copies as many items as possible from the ring buffer to the given uninitialized `slice`.
    ///
    /// The copied slots are automatically made available to be written again by the [`Producer`].
    ///
    /// Returns two sub-slices of `slice`:
    /// - The part that has been filled with data from the ring buffer (possibly empty).
    /// - The unused remainder (possibly empty).
    ///
    /// The first of the returned slices has been initialized,
    /// while the second one remains uninitialized.
    ///
    /// To copy an entire slice (and fail otherwise),
    /// [`Consumer::pop_entire_slice_uninit()`] can be used.
    /// To copy into an initialized slice, [`Consumer::pop_partial_slice()`] can be used.
    ///
    /// # Examples
    ///
    /// ```
    /// use std::mem::MaybeUninit;
    ///
    /// use rtrb::Consumer;
    ///
    /// fn pop_at_least_one_element_uninit<'a>(
    ///     c: &mut Consumer<i32>,
    ///     s: &'a mut [MaybeUninit<i32>],
    /// ) -> Result<&'a mut [MaybeUninit<i32>], &'a mut [MaybeUninit<i32>]> {
    ///     match c.pop_partial_slice_uninit(s) {
    ///         ([], remainder) => Err(remainder),
    ///         (_, remainder) => Ok(remainder),
    ///     }
    /// }
    ///
    /// fn block_while_popping_entire_slice_uninit(
    ///     c: &mut Consumer<i32>,
    ///     mut s: &mut [MaybeUninit<i32>],
    /// ) {
    ///     while let (_, remainder @ [_, ..]) = c.pop_partial_slice_uninit(s) {
    ///         std::thread::yield_now();
    ///         s = remainder;
    ///     }
    /// }
    /// ```
    ///
    /// Typically, we might get an uninitialized buffer via FFI,
    /// but in this example we are using the uninitialized part of a [`Vec`]:
    ///
    /// ```
    /// use std::mem::MaybeUninit;
    ///
    /// use rtrb::RingBuffer;
    ///
    /// let (mut producer, mut consumer) = RingBuffer::new(4);
    /// let (_, remainder) = producer.push_partial_slice(&[1, 2, 3]);
    /// assert!(remainder.is_empty());
    /// let mut buffer = Vec::with_capacity(5);
    /// let buffer_uninit = buffer.spare_capacity_mut();
    /// let (popped, remainder) = consumer.pop_partial_slice_uninit(buffer_uninit);
    /// assert_eq!(popped, [1, 2, 3]);
    /// // The returned slices are mutable ...
    /// popped[0] = -42;
    /// // ... but the second one is still uninitialized:
    /// remainder[0] = MaybeUninit::new(99);
    /// // All this happened in the uninitialized part of the buffer,
    /// // which is still "officially" empty:
    /// assert!(buffer.is_empty());
    /// // SAFETY: The first 4 elements have been initialized.
    /// unsafe {
    ///     buffer.set_len(4);
    /// }
    /// assert_eq!(buffer, [-42, 2, 3, 99]);
    /// ```
    #[inline]
    #[must_use]
    pub fn pop_partial_slice_uninit<'a>(
        &mut self,
        slice: &'a mut [MaybeUninit<T>],
    ) -> (&'a mut [T], &'a mut [MaybeUninit<T>])
    where
        T: Copy,
    {
        let slots = if self.cached_slots() < slice.len() {
            slice.len().min(self.slots())
        } else {
            slice.len()
        };
        let (buffer, remainder) = slice.split_at_mut(slots);
        // With MSRV 1.58, unwrap_unchecked() can be used.
        let popped = match self.pop_entire_slice_uninit(buffer) {
            Ok(popped) => popped,
            // SAFETY: The requested slots are available.
            Err(_) => unsafe { core::hint::unreachable_unchecked() },
        };
        (popped, remainder)
    }

    /// Copies as many items from the ring buffer as to fill the given `slice`.
    ///
    /// The copied slots are automatically made available to be written again by the [`Producer`].
    ///
    /// # Errors
    ///
    /// If not enough data is available in the ring buffer, no items are copied and
    /// a [`ChunkError`] with the available items is returned.
    ///
    /// To copy only the available slots, [`Consumer::pop_partial_slice()`] can be used.
    /// To copy into an uninitialized slice, [`Consumer::pop_entire_slice_uninit()`] can be used.
    pub fn pop_entire_slice(&mut self, slice: &mut [T]) -> Result<(), ChunkError>
    where
        T: Copy,
    {
        // SAFETY: Transmuting &mut [T] to &mut [MaybeUninit<T>] is generally unsafe!
        // However, since we can guarantee that only valid T values will ever be written,
        // and the reference never leaves our control, it should be fine.
        let _ = unsafe { self.pop_entire_slice_uninit(&mut *(slice as *mut [_] as *mut _))? };
        Ok(())
    }

    /// Copies as many items from the ring buffer as to fill the given uninitialized `slice`.
    ///
    /// The copied slots are automatically made available to be written again by the [`Producer`].
    ///
    /// Returns the given slice, but now initialized.
    ///
    /// # Errors
    ///
    /// If not enough data is available in the ring buffer, no items are copied and
    /// a [`ChunkError`] with the available items is returned.
    ///
    /// To copy only the available slots, [`Consumer::pop_partial_slice_uninit()`] can be used.
    /// To copy into an initialized slice, [`Consumer::pop_entire_slice()`] can be used.
    pub fn pop_entire_slice_uninit<'a>(
        &mut self,
        slice: &'a mut [MaybeUninit<T>],
    ) -> Result<&'a mut [T], ChunkError>
    where
        T: Copy,
    {
        let chunk = self.read_chunk(slice.len())?;
        let src = chunk.as_slice();
        // NB: If slice.is_empty(), chunk will be empty as well and the following is a no-op:
        src.copy_to_uninit(slice);
        chunk.commit_all();
        // NB: This can be replaced by `assume_init_mut()` once stabilized:
        // SAFETY: The entire `slice` has been initialized above.
        Ok(unsafe { &mut *(slice as *mut _ as *mut [_]) })
    }
}
