// Do not edit this file! It has been auto-generated from `codegen/templates/src/consumer.rs`.

use core::cell::Cell;

use crate::atomic::*;
use super::{PopError, PeekError, RingBuffer, ChunkError, chunks::ReadChunk};
use super::arc_ring_buffer::ArcRingBuffer;
use super::IS_ABANDONED;

// Only used in documentation:
#[allow(unused_imports)]
use super::Producer;

/// The consumer side of a [`RingBuffer`].
///
/// A `Consumer` can be moved between threads,
/// but references from different threads are not allowed
/// (i.e. it is [`Send`] but not [`Sync`]).
///
/// Individual elements can be moved out of the ring buffer with [`pop()`](Consumer::pop),
/// multiple elements at once can be read with [`read_chunk()`](Consumer::read_chunk).
///
/// The number of slots currently available for reading can be obtained with
/// [`slots()`](Consumer::slots).
///
/// A `Consumer` can only be created with [`RingBuffer::new()`]
/// (together with its counterpart, the [`Producer`]).
///
/// When the `Consumer` is dropped, [`Producer::is_abandoned()`] will return `true`.
/// This can be used as a crude way to communicate to the sending thread
/// that no more data will be consumed.
/// When the `Consumer` is dropped after the [`Producer`] has already been dropped,
/// all items remaining in the ring buffer will be dropped and the allocated memory
/// will be deallocated.
#[derive(Debug, PartialEq, Eq)]
pub struct Consumer<T> {
    pub(super) buffer: ArcRingBuffer<T>,
    /// A copy of `buffer.head` for quick access.
    ///
    /// This value is always in sync with `buffer.head`.
    /// For Bip Buffers, there is an exception: if `cached_head == buffer.skip`,
    /// `buffer.head` may have been reset by the producer.
    pub(super) cached_head: Cell<usize>,
    /// A copy of `buffer.tail` for quick access.
    ///
    /// This value can be stale and sometimes needs to be resynchronized
    /// with `buffer.tail`.
    pub(super) cached_tail: Cell<usize>,
}

/// It can be moved ...
/// ```
/// use rtrb::bip_arc::Consumer;
/// fn assert_send<X: Send>() {}
/// assert_send::<Consumer<u8>>();
/// ```
/// ... but not shared between threads:
/// ```compile_fail
/// # use rtrb::bip_arc::Consumer;
/// fn assert_sync<X: Sync>() {}
/// assert_sync::<Consumer<u8>>();
/// ```
// SAFETY: After moving a consumer to another thread, there is still only a single thread
// that can access the consumer side of the queue.
unsafe impl<T: Send> Send for Consumer<T>
where
    RingBuffer<T>: Sync
{}

impl<T> Consumer<T> {
    /// Attempts to pop the next element from the queue.
    ///
    /// The element is *moved* out of the ring buffer and its slot
    /// is made available to be filled by the [`Producer`] again.
    ///
    /// # Errors
    ///
    /// If the queue is empty, an error is returned.
    ///
    /// # Examples
    ///
    /// ```
    /// use rtrb::bip_arc::{PopError, RingBuffer};
    ///
    /// let (mut p, mut c) = RingBuffer::new(1);
    ///
    /// assert_eq!(p.push(10), Ok(()));
    /// assert_eq!(c.pop(), Ok(10));
    /// assert_eq!(c.pop(), Err(PopError::Empty));
    /// ```
    ///
    /// To obtain an [`Option<T>`](Option), use [`.ok()`](Result::ok) on the result.
    ///
    /// ```
    /// # use rtrb::bip_arc::RingBuffer;
    /// # let (mut p, mut c) = RingBuffer::new(1);
    /// assert_eq!(p.push(20), Ok(()));
    /// assert_eq!(c.pop().ok(), Some(20));
    /// ```
    pub fn pop(&mut self) -> Result<T, PopError> {
        if let Some(head) = self.next_head() {
            let b = &self.buffer;
            // SAFETY: head points to an initialized slot.
            let value = unsafe { b.slot_ptr(head).read() };
            let head = b.increment1(head);
            b.head.store(head, Ordering::Release);
            self.cached_head.set(head);
            Ok(value)
        } else {
            Err(PopError::Empty)
        }
    }

    /// Attempts to get read access to the next element in the queue without removing it.
    ///
    /// # Errors
    ///
    /// If the queue is empty, an error is returned.
    ///
    /// # Examples
    ///
    /// ```
    /// use rtrb::bip_arc::{PeekError, RingBuffer};
    ///
    /// let (mut p, mut c) = RingBuffer::new(1);
    ///
    /// assert_eq!(c.peek(), Err(PeekError::Empty));
    /// assert_eq!(p.push(10), Ok(()));
    /// assert_eq!(c.peek(), Ok(&10));
    /// assert_eq!(c.peek(), Ok(&10));
    /// ```
    pub fn peek(&self) -> Result<&T, PeekError> {
        if let Some(head) = self.next_head() {
            // SAFETY: head points to an initialized slot.
            Ok(unsafe { &*self.buffer.slot_ptr(head) })
        } else {
            Err(PeekError::Empty)
        }
    }

    /// Returns the number of slots available for reading.
    ///
    /// Since items can be concurrently produced on another thread, the actual number
    /// of available slots may increase at any time
    /// (up to the [`capacity()`](Consumer::capacity)).
    ///
    /// To check for a single available slot,
    /// using [`is_empty()`](Consumer::is_empty) is often quicker
    /// (because it might not have to check an atomic variable).
    ///
    /// Due to wrap-around of the internal buffer, the reported slots might not be
    /// on a contiguous segment and therefore not entirely available for reading with
    /// [`read_chunk()`](Consumer::read_chunk). To get the number of contiguous slots,
    /// [`slots_contiguous_first()`](Consumer::slots_contiguous_first) can be used.
    ///
    /// # Examples
    ///
    /// ```
    /// use rtrb::bip_arc::RingBuffer;
    ///
    /// let (mut p, mut c) = RingBuffer::new(1024);
    ///
    /// assert_eq!(c.slots(), 0);
    /// assert_eq!(p.push(0.0), Ok(()));
    /// assert_eq!(c.slots(), 1);
    /// ```
    // TODO: code reuse with other "slots" variations? benchmark using slots_contiguous()
    pub fn slots(&self) -> usize {
        let b = &self.buffer;
        let mut head = self.cached_head.get();
        let tail = b.tail.load(Ordering::Acquire);
        self.cached_tail.set(tail);
        if head == tail {
            return 0;
        }
        let collapsed_head = b.collapse_position(head);
        let collapsed_tail = b.collapse_position(tail);
        if collapsed_head < collapsed_tail {
            collapsed_tail - collapsed_head
        } else {
            let skip = b.skip.load(Ordering::Acquire);
            // TODO: code reuse with slots_contiguous..()?
            let slots_at_end = skip - collapsed_head;
            if slots_at_end != 0 {
                return collapsed_tail + slots_at_end;
            }
            // There are no more slots at the end of the buffer,
            // let's clear `skip` and wrap around!
            // TODO: the following is always true?
            if skip != b.capacity() {
                // NB: `skip` is stored before `head`.
                b.skip.store(b.capacity(), Ordering::Release);
            }
            head = b.increment(head, b.capacity() - collapsed_head);
            b.head.store(head, Ordering::Release);
            self.cached_head.set(head);
            debug_assert_eq!(b.collapse_position(head), 0);
            collapsed_tail
        }
    }

    /// Returns size of first contiguous chunk and
    /// `true` if `tail` has already been refreshed and
    /// `true` if there may be another chunk at the beginning of the buffer.
    // TODO: inline?
    fn slots_contiguous_helper(&self) -> (usize, bool, bool) {
        let b = &self.buffer;
        let mut head = self.cached_head.get();
        let mut collapsed_head = b.collapse_position(head);
        let mut tail = self.cached_tail.get();
        let mut collapsed_tail = b.collapse_position(tail);

        let mut is_empty = head == tail;
        if !is_empty && collapsed_tail <= collapsed_head {
            // NB: `skip` is only relevant if (collapsed) `tail < head`
            //     (or if the buffer is full).
            let slots = b.skip.load(Ordering::Acquire) - collapsed_head;
            if slots > 0 {
                return (slots, false, true);
            }
            b.skip.store(b.capacity(), Ordering::Release);
            head = b.increment(head, b.capacity() - collapsed_head);
            // NB: `skip` is stored before `head`.
            b.head.store(head, Ordering::Release);
            self.cached_head.set(head);
            collapsed_head = b.collapse_position(head);
            debug_assert_eq!(collapsed_head, 0);
        }
        // We have to refresh `tail` (which may wrap around).
        tail = b.tail.load(Ordering::Acquire);
        self.cached_tail.set(tail);
        collapsed_tail = b.collapse_position(tail);
        is_empty = head == tail;
        if !is_empty && collapsed_tail <= collapsed_head {
            let slots = b.skip.load(Ordering::Acquire) - collapsed_head;
            if slots > 0 {
                return (slots, true, true);
            }
            b.skip.store(b.capacity(), Ordering::Release);
            head = b.increment(head, b.capacity() - collapsed_head);
            // NB: `skip` is stored before `head`.
            b.head.store(head, Ordering::Release);
            self.cached_head.set(head);
            collapsed_head = b.collapse_position(head);
            debug_assert_eq!(collapsed_head, 0);
            (collapsed_tail, true, false)
        } else {
            (collapsed_tail - collapsed_head, true, false)
        }
    }

    /// Returns the number of slots of the next two contiguous segments available
    /// for reading with [`read_chunk()`](Consumer::read_chunk).
    ///
    /// In many cases, the second number will be `0`, but whenever the internal buffer
    /// wraps around, two contiguous segments might be available for reading.
    /// If the first number is `0`, the second will be `0` as well.
    ///
    /// The sum of both numbers is returned by [`slots()`](Consumer::slots).
    ///
    /// If you are only interested in the first number, using
    /// [`slots_contiguous_first()`](Consumer::slots_contiguous_first)
    /// should be slightly more efficient.
    ///
    /// The first number will also be reported via a [`ChunkError`] when calling
    /// [`read_chunk()`](Consumer::read_chunk) with a larger number.
    ///
    /// Since items can be concurrently produced on another thread, the actual number
    /// of available slots may increase at any time
    /// (up to a certain maximum that depends on the current read index and
    /// whether and how many slots have been skipped using
    /// [`Producer::write_chunk()`] or [`Producer::write_chunk_uninit()`],
    /// but at most up to the [`capacity()`](Consumer::capacity)).
    pub fn slots_contiguous(&self) -> (usize, usize) {
        let (slots, refreshed, try_at_beginning) = self.slots_contiguous_helper();
        // TODO: use Some(tail) instead of refreshed?
        if !try_at_beginning {
            return (slots, 0);
        }
        let b = &self.buffer;
        let tail;
        if refreshed {
            tail = self.cached_tail.get();
        } else {
            tail = b.tail.load(Ordering::Acquire);
            self.cached_tail.set(tail);
        }
        (slots, b.collapse_position(tail))
    }

    /// Returns the number of slots of the next contiguous segment available for reading with
    /// [`read_chunk()`](Consumer::read_chunk).
    ///
    /// This is the same as the first number returned by
    /// [`slots_contiguous()`](Consumer::slots_contiguous), but slightly more efficient.
    pub fn slots_contiguous_first(&self) -> usize {
        self.slots_contiguous_helper().0
    }

    /// Returns `true` if there are currently no slots available for reading.
    ///
    /// An empty ring buffer might cease to be empty at any time
    /// if the corresponding [`Producer`] is producing items in another thread.
    ///
    /// # Examples
    ///
    /// ```
    /// use rtrb::bip_arc::RingBuffer;
    ///
    /// let (mut p, mut c) = RingBuffer::new(1);
    ///
    /// assert!(c.is_empty());
    /// assert_eq!(p.push(0.0), Ok(()));
    /// assert!(!c.is_empty());
    /// ```
    ///
    /// Since items can be concurrently produced on another thread, the ring buffer
    /// might not be empty for long:
    ///
    /// ```
    /// # use rtrb::bip_arc::RingBuffer;
    /// # let (mut p, mut c) = RingBuffer::new(1);
    /// # assert_eq!(p.push(0.0), Ok(()));
    /// if c.is_empty() {
    ///     // The buffer might be empty, but it might as well not be
    ///     // if an item was just produced on another thread.
    /// }
    /// ```
    ///
    /// However, if it's not empty, another thread cannot change that:
    ///
    /// ```
    /// # use rtrb::bip_arc::RingBuffer;
    /// # let (mut p, mut c) = RingBuffer::new(1);
    /// # assert_eq!(p.push(0.0), Ok(()));
    /// if !c.is_empty() {
    ///     // At least one slot is guaranteed to be available for reading.
    /// }
    /// ```
    pub fn is_empty(&self) -> bool {
        self.next_head().is_none()
    }

    /// Returns the total capacity of the queue.
    ///
    /// See [`Producer::capacity()`] for more information.
    pub fn capacity(&self) -> usize {
        self.buffer.capacity()
    }

    /// Returns `true` if the corresponding [`Producer`] has been destroyed.
    ///
    /// TODO: update this note:
    ///
    /// Note that since Rust version 1.74.0, this is not synchronizing with the producer thread
    /// anymore, see <https://github.com/mgeier/rtrb/issues/114>.
    /// In a future version of `rtrb`, the synchronizing behavior might be restored.
    ///
    /// # Examples
    ///
    /// ```
    /// use rtrb::bip_arc::RingBuffer;
    ///
    /// let (mut p, mut c) = RingBuffer::new(7);
    /// assert!(!c.is_abandoned());
    /// assert_eq!(p.push(10), Ok(()));
    /// drop(p);
    /// assert!(c.is_abandoned());
    /// // The items that are left in the ring buffer can still be consumed:
    /// assert_eq!(c.pop(), Ok(10));
    /// ```
    ///
    /// Since the producer can be concurrently dropped on another thread,
    /// the consumer might become abandoned at any time:
    ///
    /// ```
    /// # use rtrb::bip_arc::RingBuffer;
    /// # let (mut p, mut c) = RingBuffer::new(1);
    /// # assert_eq!(p.push(10), Ok(()));
    /// if !c.is_abandoned() {
    ///     // Right now, the producer might still be alive, but it might as well not be
    ///     // if another thread has just dropped it.
    /// }
    /// ```
    ///
    /// However, if it already is abandoned, it will stay that way:
    ///
    /// ```
    /// # use rtrb::bip_arc::RingBuffer;
    /// # let (mut p, mut c) = RingBuffer::new(1);
    /// # assert_eq!(p.push(10), Ok(()));
    /// if c.is_abandoned() {
    ///     // The producer does definitely not exist anymore.
    /// }
    /// ```
    pub fn is_abandoned(&self) -> bool {
        self.buffer.flags.load(Ordering::Acquire) & IS_ABANDONED != 0
    }


    /// Get the `head` position for reading the next slot, if available.
    ///
    /// This is a strict subset of the functionality implemented in `read_chunk()`.
    /// For performance, this special case is implemented separately.
    // TODO: check if using slots_contiguous_helper() is reasonably performant for bip
    fn next_head(&self) -> Option<usize> {
        // NB: cached_head is always up-to-date, no need for atomic load here.
        let mut head = self.cached_head.get();
        let mut tail = self.cached_tail.get();
        let b = &self.buffer;

        // Check if the queue is *possibly* empty.
        if head == tail {
            // Refresh the tail ...
            tail = b.tail.load(Ordering::Acquire);
            self.cached_tail.set(tail);
            // ... and check if it's *really* empty.
            if head == tail {
                // `tail` didn't change, queue is empty.
                return None;
            } else if b.collapse_position(head) < b.collapse_position(tail) {
                // `tail` did change, but it didn't wrap around.
                return Some(head);
            }
        } else if b.collapse_position(head) < b.collapse_position(tail) {
            // The tail might have wrapped around in the meantime.
            tail = b.tail.load(Ordering::Acquire);
            self.cached_tail.set(tail);
        } else {
            // The tail cannot overtake the head, no need to refresh at this point.
        }
        debug_assert_ne!(head, tail);
        if b.collapse_position(tail) < b.collapse_position(head) {
            // NB: `skip` is only relevant if `tail < head` (both collapsed).
            let skip = b.skip.load(Ordering::Acquire);
            if b.collapse_position(head) == skip {
                // Nothing to read at the end of the buffer, wrap `head` and clear `skip`.
                // NB: `skip` is stored before `head`.
                b.skip.store(b.capacity(), Ordering::Release);
                head = b.increment(head, b.capacity() - skip);
                b.head.store(head, Ordering::Release);
                self.cached_head.set(head);

                // NB: The producer only sets `skip` if it writes at least one slot
                // at the beginning of the buffer.  Therefore, we know that the
                // wrapped-around `head` is valid for reading (at least) one slot.
            }
        }
        Some(head)
    }

    /// Prepares a chunk of `n` slots for reading.
    ///
    /// [`ReadChunk::as_slice()`]
    /// provides immutable access to the slots.
    /// After reading from those slots, they explicitly have to be made available
    /// to be written again by the [`Producer`] by calling [`ReadChunk::commit()`]
    /// or [`ReadChunk::commit_all()`].
    ///
    /// Alternatively, items can be moved out of the [`ReadChunk`] using iteration
    /// because it implements [`IntoIterator`]
    /// ([`ReadChunk::into_iter()`] can be used to explicitly turn it into an [`Iterator`]).
    /// All moved items are automatically made available to be written again by
    /// the [`Producer`].
    ///
    /// # Errors
    ///
    /// If not enough slots are available, an error
    /// (containing the number of available slots) is returned.
    /// Use
    /// [`slots_contiguous_first()`](Consumer::slots_contiguous_first)
    /// to obtain the number of available slots beforehand.
    ///
    /// # Examples
    ///
    /// See the documentation of the [`chunks`](super::chunks#examples) module.
    pub fn read_chunk(
        &mut self,
        n: usize,
    ) -> Result<ReadChunk<'_, T>, ChunkError> {
        let b = &self.buffer;
        let (slots, _, _) = self.slots_contiguous_helper();
        if slots >= n {
            // TODO: use refreshed_head.or_else(self.cached_head.get)
            let offset = b.collapse_position(self.cached_head.get());
            // SAFETY: `offset` has been set to a valid position.
            Ok(unsafe { ReadChunk::new(self, n, offset) })
        } else {
            Err(ChunkError::TooFewSlots(slots))
        }
    }
}