// DO NOT EDIT THIS FILE!
// It has been auto-generated from `codegen/templates/src/ring_buffer.rs.jinja`
// using the configuration file `codegen/configs/bip_arc.toml`.

use alloc::vec::Vec;
use core::mem::ManuallyDrop;

use super::arc_ring_buffer::ArcRingBuffer;
use crate::atomic::*;
// Padded indices to avoid false sharing.
use crate::CachePadded;

use super::{Consumer, Producer};

/// A bounded single-producer single-consumer (SPSC) queue.
///
/// Elements can be written with a [`Producer`] and read with a [`Consumer`],
/// both of which can be obtained with [`RingBuffer::new()`].
///
/// *See also the [module-level documentation](crate::bip_arc).*
#[derive(Debug)]
pub struct RingBuffer<T> {
    pub(super) head: CachePadded<AtomicUsize>,
    pub(super) tail: CachePadded<AtomicUsize>,
    // TODO: measure whether CachePadded helps
    pub(super) skip: CachePadded<AtomicUsize>,
    pub(super) flags: AtomicU8,
    /// The buffer holding slots.
    data_ptr: *mut T,
    capacity: usize,
}

// SAFETY: If T can be moved between threads, RingBuffer can as well.
unsafe impl<T: Send> Send for RingBuffer<T> {}

impl<T> RingBuffer<T> {
    fn construct(capacity: usize) -> Self {
        Self {
            head: CachePadded::new(AtomicUsize::new(0)),
            tail: CachePadded::new(AtomicUsize::new(0)),
            skip: CachePadded::new(AtomicUsize::new(capacity)),
            flags: AtomicU8::new(0),
            data_ptr: ManuallyDrop::new(Vec::with_capacity(capacity)).as_mut_ptr(),
            capacity,
        }
    }

    pub(super) fn capacity(&self) -> usize {
        self.capacity
    }

    pub(super) fn data_ptr(&self) -> *mut T {
        self.data_ptr
    }
}

impl<T> Drop for RingBuffer<T> {
    /// Drops all non-empty slots and deallocates the storage.
    fn drop(&mut self) {
        // SAFETY: this is called exactly once, no references to any elements exist anymore.
        unsafe { self.drop_all_elements() };

        // Finally, deallocate the buffer, but don't run any destructors.
        // SAFETY: data_ptr and capacity are still valid from the original initialization.
        unsafe { Vec::from_raw_parts(self.data_ptr, 0, self.capacity()) };
    }
}

/// A `RingBuffer` can be shared between threads.
///
/// `T` does not need to be `Sync`, because we never share it across threads.
/// For example, [`std::cell::Cell`] is `Send` but not `Sync`:
///
/// ```
/// fn assert_sync<X: Sync>() {}
/// assert_sync::<rtrb::bip_arc::RingBuffer<std::cell::Cell<u8>>>();
/// ```
// SAFETY: RingBuffer is only mutated (using *interior mutablility*)
// via Producer/Consumer (which are !Sync), all other access can be shared.
unsafe impl<T> Sync for RingBuffer<T> {}

// NB: `Send` might be implemented by different storage backends,
// but it is not necessary for correct behavior of the RingBuffer.

impl<T> PartialEq for RingBuffer<T> {
    fn eq(&self, other: &Self) -> bool {
        core::ptr::eq(self, other)
    }
}

impl<T> Eq for RingBuffer<T> {}

impl<T> RingBuffer<T> {
    /// Creates a ring buffer with the given `capacity`
    /// and returns [`Producer`] and [`Consumer`].
    ///
    /// # Examples
    ///
    /// ```
    /// use rtrb::bip_arc::RingBuffer;
    ///
    /// let (p, c) = RingBuffer::<f32>::new(100);
    /// ```
    ///
    /// Specifying an explicit type
    /// with the [turbofish](https://turbo.fish/)
    /// is is only necessary if it cannot be deduced by the compiler.
    ///
    /// ```
    /// use rtrb::bip_arc::RingBuffer;
    ///
    /// let (mut p, c) = RingBuffer::new(100);
    /// assert_eq!(p.push(0.0f32), Ok(()));
    /// ```
    #[allow(clippy::new_ret_no_self)]
    pub fn new(capacity: usize) -> (Producer<T>, Consumer<T>) {
        let capacity = Self::update_capacity(capacity);
        ArcRingBuffer::new(Self::construct(capacity))
    }

    const fn update_capacity(capacity: usize) -> usize {
        // No need to update, we are not relying on power-of-two sizes.
        capacity
    }

    /// Drop all elements that are still in the buffer.
    ///
    /// After this, head and tail indices are invalid.
    ///
    /// # Safety
    ///
    /// This can only be called in the `Drop` implementation of the ring buffer.
    ///
    /// The threads must have been synchronized before via `self.flags`.
    #[inline(never)]
    unsafe fn drop_all_elements(&mut self) {
        // These atomic variables are *not* used for synchronizing the threads
        // before destruction.  Relaxed ordering is sufficient here.
        let mut head = self.head.load(Ordering::Relaxed);
        let tail = self.tail.load(Ordering::Relaxed);
        let skip = self.skip.load(Ordering::Relaxed);
        // Loop over all slots that hold a value and drop them.
        while head != tail {
            if self.collapse_position(head) == skip {
                head = self.increment(head, self.capacity() - skip);
            }
            // SAFETY: All slots between head and tail have been initialized.
            unsafe { self.slot_ptr(head).drop_in_place() };
            head = self.increment1(head);
        }
    }

    pub(super) fn collapse_position(&self, pos: usize) -> usize {
        // Wraps from the range `0 .. 2 * capacity` to `0 .. capacity`.
        debug_assert!(pos == 0 || pos < 2 * self.capacity());
        if pos < self.capacity() {
            pos
        } else {
            pos - self.capacity()
        }
    }

    /// Returns a pointer to the (possibly uninitialized) slot at position `pos`.
    ///
    /// # Safety
    ///
    /// `pos` must be valid.
    ///
    /// If `pos == 0 && capacity == 0`, the returned pointer must not be dereferenced!
    pub(super) unsafe fn slot_ptr(&self, pos: usize) -> *mut T {
        // SAFETY: See docstring.
        unsafe { self.data_ptr().add(self.collapse_position(pos)) }
    }

    /// Increments a position by going `n` slots forward.
    pub(super) fn increment(&self, pos: usize, n: usize) -> usize {
        debug_assert!(pos == 0 || pos < 2 * self.capacity());
        debug_assert!(n <= self.capacity());
        let threshold = 2 * self.capacity() - n;
        if pos < threshold {
            pos + n
        } else {
            pos - threshold
        }
    }

    /// Increments a position by going one slot forward.
    ///
    /// This might be more efficient than self.increment(..., 1).
    pub(super) fn increment1(&self, pos: usize) -> usize {
        debug_assert_ne!(self.capacity(), 0);
        debug_assert!(pos < 2 * self.capacity());
        if pos < 2 * self.capacity() - 1 {
            pos + 1
        } else {
            0
        }
    }

    /// Returns the distance between two positions.
    pub(super) fn distance(&self, a: usize, b: usize) -> usize {
        debug_assert!(a == 0 || a < 2 * self.capacity());
        debug_assert!(b == 0 || b < 2 * self.capacity());
        if a <= b {
            b - a
        } else {
            2 * self.capacity() - a + b
        }
    }
}
