// DO NOT EDIT THIS FILE!
// It has been auto-generated from `codegen/templates/src/mod.rs.jinja`
// using the configuration file `codegen/configs/array.toml`.

//! TODO: array docs
//!
//! # Usage
//!
//! A [`RingBuffer`] consists of two parts:
//! a [`Producer`] for writing into the ring buffer and
//! a [`Consumer`] for reading from the ring buffer.
//!
//! TODO: more usage instructions
//!
//! # Examples
//!
//! Moving single elements into and out of a queue with
//! [`Producer::push()`] and [`Consumer::pop()`], respectively:
//!
//! ```
//! use rtrb::array::{RingBuffer, PushError, PopError};
//!
//! let rb = RingBuffer::<_, 2>::new();
//! let mut p = rb.producer().unwrap();
//! let mut c = rb.consumer().unwrap();
//!
//! assert_eq!(p.push(10), Ok(()));
//! assert_eq!(p.push(20), Ok(()));
//! assert_eq!(p.push(30), Err(PushError::Full(30)));
//!
//! std::thread::scope(|s| {
//!     s.spawn(move || {
//!         assert_eq!(c.pop(), Ok(10));
//!         assert_eq!(c.pop(), Ok(20));
//!         assert_eq!(c.pop(), Err(PopError::Empty));
//!     });
//! });
//! ```
//!
//! See the documentation of the [`chunks#examples`] module
//! for examples that write multiple items at once with
//! [`Producer::write_chunk_uninit()`] and [`Producer::write_chunk()`]
//! and read multiple items with [`Consumer::read_chunk()`].

const HAS_PRODUCER: u8 = 0b10000000;
const HAS_CONSUMER: u8 = 0b01000000;

mod ring_buffer;
pub use ring_buffer::RingBuffer;
mod producer;
pub use producer::Producer;
mod consumer;
pub use consumer::Consumer;

pub mod chunks;

// Only used in documentation:
#[allow(unused_imports)]
use chunks::WriteChunkUninit;

/// Error type for [`Consumer::peek()`].
#[doc(inline)]
pub use crate::PeekError;

/// Error type for [`Consumer::pop()`].
#[doc(inline)]
pub use crate::PopError;

/// Error type for [`Producer::push()`].
#[doc(inline)]
pub use crate::PushError;

/// Error type for [`Producer::write_chunk()`], [`Producer::write_chunk_uninit()`]
/// and [`Consumer::read_chunk()`].
///
/// To get the maximum number of available slots beforehand
/// (and therefore avoid this error), use
/// [`Producer::slots()`] and [`Consumer::slots()`],
/// respectively.
#[doc(inline)]
pub use crate::ChunkError;

/// Extension trait providing a [`copy_to_uninit()`](CopyToUninit::copy_to_uninit)
/// method on built-in slices.
///
/// This can be used to safely copy data to the
/// slices returned from [`WriteChunkUninit::as_mut_slices()`].
///
/// To use this, the trait has to be brought into scope, e.g. with:
///
/// ```
/// use rtrb::array::CopyToUninit as _;
/// ```
///
/// TODO: update link:
///
/// For a usage example, see [`crate::chunks`](crate::chunks#common-access-patterns).
#[doc(inline)]
pub use crate::CopyToUninit;
