// Do not edit this file! It has been auto-generated from `codegen/templates/src/producer.rs`.

use core::cell::Cell;

use super::{PushError, RingBuffer};

/// The producer side of a [`RingBuffer`].
///
/// A `Producer` can be moved between threads,
/// but references from different threads are not allowed
/// (i.e. it is [`Send`] but not [`Sync`]).
///
/// Individual elements can be moved into the ring buffer with [`push()`](Producer::push),
/// multiple elements at once can be written with [`write_chunk()`](Producer::write_chunk)
/// and [`write_chunk_uninit()`](Producer::write_chunk_uninit).
///
/// The number of free slots currently available for writing can be obtained with
/// [`slots()`](Producer::slots).
///
/// A `Producer` can only be created with [`RingBuffer::producer()`].
#[derive(Debug, PartialEq, Eq)]
pub struct Producer<'a, T, const N: usize> {
    buffer: &'a RingBuffer<T, N>,
    cached_head: Cell<usize>,
    cached_tail: Cell<usize>,
}

impl<T, const N: usize> Drop for Producer<'_, T, N> {
    fn drop(&mut self) {
        let _ = self.buffer.flags.fetch_and(!HAS_PRODUCER, Ordering::SeqCst);
    }
}

/// It can be moved ...
/// ```
/// use rtrb::array::Producer;
/// fn assert_send<X: Send>() {}
/// assert_send::<Producer<u8, 8>>();
/// ```
/// ... but not shared between threads:
/// ```compile_fail
/// # use rtrb::array::Producer;
/// fn assert_sync<X: Sync>() {}
/// assert_sync::<Producer<u8, 8>>();
/// ```
// SAFETY: After moving a producer to another thread, there is still only a single thread
// that can access the producer side of the queue.
unsafe impl<T: Send, const N: usize> Send for Producer<'_, T, N>
where
    RingBuffer<T, N>: Sync
{}

impl<T, const N: usize> Producer<'_, T, N> {
    /// Attempts to push an element into the queue.
    ///
    /// The element is *moved* into the ring buffer and its slot
    /// is made available to be read by the [`Consumer`].
    ///
    /// # Errors
    ///
    /// If the queue is full, the element is returned back as an error.
    ///
    /// # Examples
    ///
    /// ```
    /// use rtrb::array::{PushError, RingBuffer};
    ///
    /// let rb = RingBuffer::<_, 1>::new();
    /// let mut p = rb.producer().unwrap();
    /// let mut c = rb.consumer().unwrap();

    ///
    /// assert_eq!(p.push(10), Ok(()));
    /// assert_eq!(p.push(20), Err(PushError::Full(20)));
    /// ```
    pub fn push(&mut self, value: T) -> Result<(), PushError<T>> {
        if let Some(tail) = self.next_tail() {
            let b = &self.buffer;
            // SAFETY: tail points to an empty slot.
            unsafe { b.slot_ptr(tail).write(value) };
            let tail = b.increment1(tail);
            b.tail.store(tail, Ordering::Release);
            self.cached_tail.set(tail);
            Ok(())
        } else {
            Err(PushError::Full(value))
        }
    }

    /// Returns the number of slots available for writing.
    ///
    /// Since items can be concurrently consumed on another thread, the actual number
    /// of available slots may increase at any time
    /// (up to the [`capacity()`](Producer::capacity)).
    ///
    /// To check for a single available slot,
    /// using [`is_full()`](Producer::is_full) is often quicker
    /// (because it might not have to check an atomic variable).
    ///
    /// # Examples
    ///
    /// ```
    /// use rtrb::array::RingBuffer;
    ///
    /// let rb = RingBuffer::<_, 4096>::new();
    /// let mut p = rb.producer().unwrap();
    /// let mut c = rb.consumer().unwrap();

    /// assert_eq!(p.push(0.5f32), Ok(()));
    ///
    /// assert_eq!(p.slots(), 4095);
    /// ```
    pub fn slots(&self) -> usize {
        let b = &self.buffer;
        let head = b.head.load(Ordering::Acquire);
        self.cached_head.set(head);
        b.capacity() - b.distance(head, self.cached_tail.get())
    }

    /// Returns `true` if there are currently no slots available for writing.
    ///
    /// A full ring buffer might cease to be full at any time
    /// if the corresponding [`Consumer`] is consuming items in another thread.
    ///
    /// # Examples
    ///
    /// ```
    /// use rtrb::array::RingBuffer;
    ///
    /// let rb = RingBuffer::<_, 1>::new();
    /// let mut p = rb.producer().unwrap();
    /// let mut c = rb.consumer().unwrap();

    ///
    /// assert!(!p.is_full());
    /// assert_eq!(p.push(10), Ok(()));
    /// assert!(p.is_full());
    /// ```
    ///
    /// Since items can be concurrently consumed on another thread, the ring buffer
    /// might not be full for long:
    ///
    /// ```
    /// # use rtrb::array::RingBuffer;
    /// # let rb = RingBuffer::<_, 1>::new();
    /// # let mut p = rb.producer().unwrap();
    /// # let mut c = rb.consumer().unwrap();

    /// # assert_eq!(p.push(10), Ok(()));
    /// if p.is_full() {
    ///     // The buffer might be full, but it might as well not be
    ///     // if an item was just consumed on another thread.
    /// }
    /// ```
    ///
    /// However, if it's not full, another thread cannot change that:
    ///
    /// ```
    /// # use rtrb::array::RingBuffer;
    /// # let rb = RingBuffer::<_, 1>::new();
    /// # let mut p = rb.producer().unwrap();
    /// # let mut c = rb.consumer().unwrap();

    /// # assert_eq!(p.push(10), Ok(()));
    /// if !p.is_full() {
    ///     // At least one slot is guaranteed to be available for writing.
    /// }
    /// ```
    pub fn is_full(&self) -> bool {
        self.next_tail().is_none()
    }

    /// Returns the total capacity of the queue.
    ///
    /// At any time, the capacity is subdivided into
    /// [`Producer::slots()`] available for writing and
    /// [`Consumer::slots()`] available for
    /// reading.
    ///
    /// # Examples
    ///
    /// ```
    /// use rtrb::array::RingBuffer;
    ///
    /// let rb = RingBuffer::<_, 4096>::new();
    /// let mut p = rb.producer().unwrap();
    /// let mut c = rb.consumer().unwrap();

    ///
    /// assert_eq!(p.push(-0.7), Ok(()));
    /// assert_eq!(p.slots(), 4095);
    /// assert_eq!(c.slots(), 1);
    /// assert_eq!(p.capacity(), 4096);
    /// assert_eq!(c.capacity(), 4096);
    /// ```
    pub fn capacity(&self) -> usize {
        self.buffer.capacity()
    }

    /// Returns `true` if the [`RingBuffer`] connected to this `Producer`
    /// is also connected to a [`Consumer`].
    ///
    /// This can change at any time when another thread creates or drops a `Consumer`.
    ///
    /// See also [`RingBuffer::has_consumer()`].
    pub fn has_consumer(&self) -> bool {
        self.buffer.flags.load(Ordering::SeqCst) & HAS_CONSUMER != 0
    }

    /// Get the tail position for writing the next slot, if available.
    ///
    /// This is a strict subset of the functionality implemented in `write_chunk_uninit()`.
    /// For performance, this special case is implemented separately.
    fn next_tail(&self) -> Option<usize> {
        let head = self.cached_head.get();
        let tail = self.cached_tail.get();
        let b = &self.buffer;
        // Check if the queue is *possibly* full.
        if b.distance(head, tail) == b.capacity() {
            // Refresh the head ...
            let head = b.head.load(Ordering::Acquire);
            self.cached_head.set(head);
            // ... and check if it's *really* full.
            if b.distance(head, tail) == b.capacity() {
                // `head` didn't change, the buffer is definitely full.
                return None;
            }
        }
        Some(tail)
    }

    //fn_producer_write_chunk!(N = $N, bip = $bip, contiguous = $contiguous);
    //fn_producer_write_chunk_uninit!(N = $N, bip = $bip, contiguous = $contiguous);
}