// DO NOT EDIT THIS FILE!
// It has been auto-generated from `codegen/templates/src/ring_buffer.rs.jinja`
// using the configuration file `codegen/configs/array2.toml`.

use core::cell::UnsafeCell;
use core::mem::MaybeUninit;

use crate::atomic::*;
// Padded indices to avoid false sharing.
use crate::CachePadded;

use super::{Consumer, Producer};

const HAS_PRODUCER: u8 = 0b10000000;
const HAS_CONSUMER: u8 = 0b01000000;

/// A bounded single-producer single-consumer (SPSC) queue.
///
/// Elements can be written with a [`Producer`] and read with a [`Consumer`],
/// which can be obtained with [`RingBuffer::producer()`]
/// and [`RingBuffer::consumer()`], respectively.
///
/// *See also the [module-level documentation](crate::array2).*
#[derive(Debug, PartialEq, Eq)]
#[repr(transparent)]
pub struct RingBuffer<T, const N: usize>(RingBufferInner<[MaybeUninit<T>; N]>);

#[derive(Debug)]
pub(super) struct RingBufferInner<Container: ?Sized> {
    head: CachePadded<AtomicUsize>,
    tail: CachePadded<AtomicUsize>,
    flags: AtomicU8,
    /// The possibly unsized container holding slots.
    ///
    /// This must be in an `UnsafeCell` because both producer and consumer
    /// have a (non-mutable) reference to the ring buffer and they use
    /// *interior mutability* to modify it.
    slots: UnsafeCell<Container>,
}

pub(super) type RingBufferUnsized<T> = RingBufferInner<[MaybeUninit<T>]>;

// SAFETY: If T can be moved between threads, RingBuffer can as well.
unsafe impl<T: Send, const N: usize> Send for RingBuffer<T, N> {}

// SAFETY: This can be shared, even if T is not Sync.
unsafe impl<Container: ?Sized> Sync for RingBufferInner<Container> {}

impl<T, const N: usize> RingBuffer<T, N> {
    const fn construct() -> Self {
        RingBuffer(RingBufferInner {
            head: CachePadded::new(AtomicUsize::new(0)),
            tail: CachePadded::new(AtomicUsize::new(0)),
            flags: AtomicU8::new(0),
            slots: UnsafeCell::new([const { MaybeUninit::uninit() }; N]),
        })
    }
}

impl<T, const N: usize> Drop for RingBuffer<T, N> {
    fn drop(&mut self) {
        let inner: &mut RingBufferUnsized<T> = &mut self.0;
        // SAFETY: this is called exactly once, no references to any elements exist anymore.
        unsafe { inner.drop_all_elements() };
    }
}

impl<T, const N: usize> Default for RingBuffer<T, N> {
    fn default() -> Self {
        Self::new()
    }
}

impl<T> RingBufferUnsized<T> {
    pub(super) fn data_ptr(&self) -> *mut T {
        // TODO: what happens if N == 0?
        self.slots.get().cast()
    }

    pub(super) fn capacity(&self) -> usize {
        self.slots.get().len()
    }

    pub(super) fn has_producer(&self) -> bool {
        // TODO: Avoid code duplication with RingBuffer<T, N>::has_producer()?
        self.flags.load(Ordering::SeqCst) & HAS_PRODUCER != 0
    }

    pub(super) fn has_consumer(&self) -> bool {
        // TODO: Avoid code duplication with RingBuffer<T, N>::has_consumer()?
        self.flags.load(Ordering::SeqCst) & HAS_CONSUMER != 0
    }
}

/// A `RingBuffer` can be shared between threads.
///
/// `T` does not need to be `Sync`, because we never share it across threads.
/// For example, [`std::cell::Cell`] is `Send` but not `Sync`:
///
/// ```
/// fn assert_sync<X: Sync>() {}
/// assert_sync::<rtrb::array2::RingBuffer<std::cell::Cell<u8>, 8>>();
/// ```
// SAFETY: RingBuffer is only mutated (using *interior mutablility*)
// via Producer/Consumer (which are !Sync), all other access can be shared.
unsafe impl<T, const N: usize> Sync for RingBuffer<T, N> {}

// NB: `Send` might be implemented by different storage backends,
// but it is not necessary for correct behavior of the RingBuffer.

impl<Container: ?Sized> PartialEq for RingBufferInner<Container> {
    fn eq(&self, other: &Self) -> bool {
        core::ptr::eq(self, other)
    }
}

impl<Container: ?Sized> Eq for RingBufferInner<Container> {}

impl<T, const N: usize> RingBuffer<T, N> {
    /// Creates a ring buffer with a capacity of `N`.
    ///
    /// `N` must be a power of two.
    ///
    /// A (single) [`Producer`] for writing into the ring buffer can be created with
    /// [`RingBuffer::producer()`].
    /// A (single) [`Consumer`] for reading from the ring buffer can be created with
    /// [`RingBuffer::consumer()`].
    ///
    /// # Examples
    ///
    /// ```
    /// use rtrb::array2::RingBuffer;
    ///
    /// let rb = RingBuffer::<f32, 128>::new();
    /// ```
    ///
    /// Specifying an explicit type
    /// is is only necessary if it cannot be deduced by the compiler.
    ///
    /// ```
    /// use rtrb::array2::RingBuffer;
    ///
    /// let rb = RingBuffer::<_, 128>::new();
    /// let mut producer = rb.producer().unwrap();
    /// assert_eq!(producer.push(0.0f32), Ok(()));
    /// ```
    ///
    /// See the [module-level documentation](crate::array2) for `static` usage.
    pub const fn new() -> Self {
        const {
            assert!(Self::update_capacity(N) == N, "`N` must be a power of two");
        }
        Self::construct()
    }

    /// Creates a [`Producer`] (if it doesn't exist yet) for writing into the `RingBuffer`.
    ///
    /// # Examples
    ///
    /// Only one producer and one consumer can exist at once,
    /// but once a producer has been dropped, a new one can be created:
    /// ```
    /// use rtrb::array2::RingBuffer;
    ///
    /// let rb = RingBuffer::<_, 64>::new();
    /// let mut producer = rb.producer().unwrap();
    /// let mut consumer = rb.consumer().unwrap();
    /// assert!(rb.producer().is_none());
    /// assert_eq!(producer.push(10), Ok(()));
    /// drop(producer);
    /// assert!(!consumer.has_producer());
    /// assert!(!rb.has_producer());
    /// let mut producer = rb.producer().unwrap();
    /// assert!(consumer.has_producer());
    /// assert!(rb.has_producer());
    /// assert_eq!(producer.push(20), Ok(()));
    /// assert_eq!(consumer.pop(), Ok(10));
    /// assert_eq!(consumer.pop(), Ok(20));
    /// ```
    pub fn producer(&self) -> Option<Producer<'_, T>> {
        use core::cell::Cell;
        let old_flags = self.0.flags.fetch_or(HAS_PRODUCER, Ordering::SeqCst);
        if old_flags & HAS_PRODUCER == 0 {
            let head = self.0.head.load(Ordering::Relaxed);
            let tail = self.0.tail.load(Ordering::Relaxed);
            Some(Producer {
                buffer: &self.0,
                cached_head: Cell::new(head),
                cached_tail: Cell::new(tail),
            })
        } else {
            None
        }
    }

    /// Creates a [`Consumer`] (if it doesn't exist yet) for reading from the `RingBuffer`.
    ///
    /// # Examples
    ///
    /// Only one producer and one consumer can exist at once,
    /// but once a consumer has been dropped, a new one can be created:
    /// ```
    /// use rtrb::array2::RingBuffer;
    ///
    /// let rb = RingBuffer::<_, 64>::new();
    /// let mut producer = rb.producer().unwrap();
    /// let mut consumer = rb.consumer().unwrap();
    /// assert!(rb.consumer().is_none());
    /// assert_eq!(producer.push(10), Ok(()));
    /// assert_eq!(producer.push(20), Ok(()));
    /// assert_eq!(consumer.pop(), Ok(10));
    /// drop(consumer);
    /// assert!(!producer.has_consumer());
    /// assert!(!rb.has_consumer());
    /// let mut consumer = rb.consumer().unwrap();
    /// assert!(producer.has_consumer());
    /// assert!(rb.has_consumer());
    /// assert_eq!(consumer.pop(), Ok(20));
    /// ```
    pub fn consumer(&self) -> Option<Consumer<'_, T>> {
        use core::cell::Cell;
        let old_flags = self.0.flags.fetch_or(HAS_CONSUMER, Ordering::SeqCst);
        if old_flags & HAS_CONSUMER == 0 {
            let head = self.0.head.load(Ordering::Relaxed);
            let tail = self.0.tail.load(Ordering::Relaxed);
            Some(Consumer {
                buffer: &self.0,
                cached_head: Cell::new(head),
                cached_tail: Cell::new(tail),
            })
        } else {
            None
        }
    }

    /// Returns `true` if a [`Producer`] exists for this `RingBuffer`.
    ///
    /// If not, it can be created with [`producer()`](RingBuffer::producer).
    ///
    /// See also [`Consumer::has_producer()`].
    pub fn has_producer(&self) -> bool {
        self.0.flags.load(Ordering::SeqCst) & HAS_PRODUCER != 0
    }

    /// Returns `true` if a [`Consumer`] exists for this `RingBuffer`.
    ///
    /// If not, it can be created with [`consumer()`](RingBuffer::consumer).
    ///
    /// See also [`Producer::has_consumer()`].
    pub fn has_consumer(&self) -> bool {
        self.0.flags.load(Ordering::SeqCst) & HAS_CONSUMER != 0
    }

    const fn update_capacity(capacity: usize) -> usize {
        capacity.next_power_of_two()
    }
}

impl<T> RingBufferUnsized<T> {
    /// Drop all elements that are still in the buffer.
    ///
    /// After this, head and tail indices are invalid.
    ///
    /// # Safety
    ///
    /// This can only be called in the `Drop` implementation of the ring buffer.
    ///
    /// The threads must have been synchronized before via `self.flags`.
    #[inline(never)]
    unsafe fn drop_all_elements(&mut self) {
        // These atomic variables are *not* used for synchronizing the threads
        // before destruction.  Relaxed ordering is sufficient here.
        let mut head = self.head.load(Ordering::Relaxed);
        let tail = self.tail.load(Ordering::Relaxed);
        // Loop over all slots that hold a value and drop them.
        while head != tail {
            // SAFETY: All slots between head and tail have been initialized.
            unsafe { self.slot_ptr(head).drop_in_place() };
            head = self.increment1(head);
        }
    }

    pub(super) fn collapse_position(&self, pos: usize) -> usize {
        // Wraps from any number to the range `0 .. capacity`.
        // TODO: is capacity 0 supported?
        pos & (self.capacity() - 1)
    }

    /// Returns a pointer to the (possibly uninitialized) slot at position `pos`.
    ///
    /// # Safety
    ///
    /// `pos` must be valid.
    ///
    /// If `pos == 0 && capacity == 0`, the returned pointer must not be dereferenced!
    pub(super) unsafe fn slot_ptr(&self, pos: usize) -> *mut T {
        // SAFETY: See docstring.
        unsafe { self.data_ptr().add(self.collapse_position(pos)) }
    }

    /// Increments a position by going `n` slots forward.
    pub(super) fn increment(&self, pos: usize, n: usize) -> usize {
        pos.wrapping_add(n)
    }

    /// Increments a position by going one slot forward.
    ///
    /// This might be more efficient than self.increment(..., 1).
    pub(super) fn increment1(&self, pos: usize) -> usize {
        pos.wrapping_add(1)
    }

    /// Returns the distance between two positions.
    pub(super) fn distance(&self, a: usize, b: usize) -> usize {
        b.wrapping_sub(a)
    }

    pub(super) fn head(&self) -> usize {
        self.head.load(Ordering::Acquire)
    }

    pub(super) fn set_head(&self, value: usize) {
        self.head.store(value, Ordering::Release);
    }

    pub(super) fn tail(&self) -> usize {
        self.tail.load(Ordering::Acquire)
    }

    pub(super) fn set_tail(&self, value: usize) {
        self.tail.store(value, Ordering::Release);
    }

    pub(super) fn drop_producer(&self) {
        let _ = self.flags.fetch_and(!HAS_PRODUCER, Ordering::SeqCst);
    }

    pub(super) fn drop_consumer(&self) {
        let _ = self.flags.fetch_and(!HAS_CONSUMER, Ordering::SeqCst);
    }
}
