// Do not edit this file! It has been auto-generated from `codegen/templates/src/mod.rs`.

//! TODO: arc2 docs


use alloc::vec::Vec;
use core::mem::ManuallyDrop;

use crate::atomic::*;
// Padded indices to avoid false sharing.
use crate::CachePadded;

/// A bounded single-producer single-consumer (SPSC) queue.
///
/// Elements can be written with a [`Producer`] and read with a [`Consumer`],
/// both of which can be obtained with [`RingBuffer::new()`].
///
/// *See also the [module-level documentation](rtrb::arc2).*
#[derive(Debug)]
pub struct RingBuffer<T> {
    head: CachePadded<AtomicUsize>,
    tail: CachePadded<AtomicUsize>,
    flags: AtomicU8,
    /// The buffer holding slots.
    data_ptr: *mut T,
    capacity: usize,
}

// SAFETY: If T can be moved between threads, RingBuffer can as well.
unsafe impl<T: Send> Send for RingBuffer<T> {}

impl<T> RingBuffer<T> {
    // Private helper function.
    fn construct(capacity: usize) -> Self {
        Self {
            head: CachePadded::new(AtomicUsize::new(0)),
            tail: CachePadded::new(AtomicUsize::new(0)),
            flags: AtomicU8::new(0),
            data_ptr: ManuallyDrop::new(Vec::with_capacity(capacity)).as_mut_ptr(),
            capacity,
        }
    }

    fn capacity(&self) -> usize {
        self.capacity
    }

    fn data_ptr(&self) -> *mut T {
        self.data_ptr
    }
}

impl<T> Drop for RingBuffer<T> {
    /// Drops all non-empty slots and deallocates the storage.
    fn drop(&mut self) {
        // SAFETY: this is called exactly once, no references to any elements exist anymore.
        unsafe { self.drop_all_elements() };

        // Finally, deallocate the buffer, but don't run any destructors.
        // SAFETY: data_ptr and capacity are still valid from the original initialization.
        unsafe { Vec::from_raw_parts(self.data_ptr, 0, self.capacity()) };
    }
}

