// DO NOT EDIT THIS FILE!
// It has been auto-generated from `codegen/templates/src/consumer.rs.jinja`
// using the configuration file `codegen/configs/bip_array.toml`.

use core::cell::Cell;

use super::{chunks::ReadChunk, ChunkError, PeekError, PopError};
use super::ring_buffer::RingBufferUnsized;
use super::{HAS_CONSUMER, HAS_PRODUCER};
use crate::atomic::*;

// Only used in documentation:
#[allow(unused_imports)]
use super::Producer;

/// The consumer side of a [`RingBuffer`].
///
/// A `Consumer` can be moved between threads,
/// but references from different threads are not allowed
/// (i.e. it is [`Send`] but not [`Sync`]).
///
/// Individual elements can be moved out of the ring buffer with [`pop()`](Consumer::pop),
/// multiple elements at once can be read with [`read_chunk()`](Consumer::read_chunk).
///
/// The number of slots currently available for reading can be obtained with
/// [`slots()`](Consumer::slots).
///
/// A `Consumer` can only be created with [`RingBuffer::consumer()`].
#[derive(Debug, PartialEq, Eq)]
pub struct Consumer<'a, T> {
    pub(super) buffer: &'a RingBufferUnsized<T>,
    pub(super) cached_head: Cell<usize>,
    pub(super) cached_tail: Cell<usize>,
}

impl<T> Drop for Consumer<'_, T> {
    fn drop(&mut self) {
        let _ = self.buffer.flags.fetch_and(!HAS_CONSUMER, Ordering::SeqCst);
    }
}

/// It can be moved ...
/// ```
/// use rtrb::bip_array::Consumer;
/// fn assert_send<X: Send>() {}
/// assert_send::<Consumer<u8>>();
/// ```
/// ... but not shared between threads:
/// ```compile_fail
/// # use rtrb::bip_array::Consumer;
/// fn assert_sync<X: Sync>() {}
/// assert_sync::<Consumer<u8>>();
/// ```
// SAFETY: After moving a consumer to another thread, there is still only a single thread
// that can access the consumer side of the queue.
unsafe impl<T: Send> Send for Consumer<'_, T> where RingBufferUnsized<T>: Sync {}

impl<T> Consumer<'_, T> {
    /// Attempts to pop the next element from the queue.
    ///
    /// The element is *moved* out of the ring buffer and its slot
    /// is made available to be filled by the [`Producer`] again.
    ///
    /// # Errors
    ///
    /// If the queue is empty, an error is returned.
    ///
    /// # Examples
    ///
    /// ```
    /// use rtrb::bip_array::{PopError, RingBuffer};
    ///
    /// let rb = RingBuffer::<_, 1>::new();
    /// let mut p = rb.producer().unwrap();
    /// let mut c = rb.consumer().unwrap();
    ///
    /// assert_eq!(p.push(10), Ok(()));
    /// assert_eq!(c.pop(), Ok(10));
    /// assert_eq!(c.pop(), Err(PopError::Empty));
    /// ```
    ///
    /// To obtain an [`Option<T>`](Option), use [`.ok()`](Result::ok) on the result.
    ///
    /// ```
    /// # use rtrb::bip_array::RingBuffer;
    /// # let rb = RingBuffer::<_, 1>::new();
    /// # let mut p = rb.producer().unwrap();
    /// # let mut c = rb.consumer().unwrap();
    /// assert_eq!(p.push(20), Ok(()));
    /// assert_eq!(c.pop().ok(), Some(20));
    /// ```
    pub fn pop(&mut self) -> Result<T, PopError> {
        if let Some(head) = self.next_head() {
            let b = &self.buffer;
            // SAFETY: head points to an initialized slot.
            let value = unsafe { b.slot_ptr(head).read() };
            let head = b.increment1(head);
            b.head.store(head, Ordering::Release);
            self.cached_head.set(head);
            Ok(value)
        } else {
            Err(PopError::Empty)
        }
    }

    /// Attempts to get read access to the next element in the queue without removing it.
    ///
    /// # Errors
    ///
    /// If the queue is empty, an error is returned.
    ///
    /// # Examples
    ///
    /// ```
    /// use rtrb::bip_array::{PeekError, RingBuffer};
    ///
    /// let rb = RingBuffer::<_, 1>::new();
    /// let mut p = rb.producer().unwrap();
    /// let mut c = rb.consumer().unwrap();
    ///
    /// assert_eq!(c.peek(), Err(PeekError::Empty));
    /// assert_eq!(p.push(10), Ok(()));
    /// assert_eq!(c.peek(), Ok(&10));
    /// assert_eq!(c.peek(), Ok(&10));
    /// ```
    pub fn peek(&self) -> Result<&T, PeekError> {
        if let Some(head) = self.next_head() {
            // SAFETY: head points to an initialized slot.
            Ok(unsafe { &*self.buffer.slot_ptr(head) })
        } else {
            Err(PeekError::Empty)
        }
    }

    /// Returns the number of slots available for reading.
    ///
    /// Since items can be concurrently produced on another thread, the actual number
    /// of available slots may increase at any time
    /// (up to the [`capacity()`](Consumer::capacity)).
    ///
    /// To check for a single available slot,
    /// using [`is_empty()`](Consumer::is_empty) is often quicker
    /// (because it might not have to check an atomic variable).
    ///
    /// Due to wrap-around of the internal buffer, the reported slots might not be
    /// on a contiguous segment and therefore not entirely available for reading with
    /// [`read_chunk()`](Consumer::read_chunk). To get the number of contiguous slots,
    /// [`slots_contiguous_first()`](Consumer::slots_contiguous_first) can be used.
    ///
    /// # Examples
    ///
    /// ```
    /// use rtrb::bip_array::RingBuffer;
    ///
    /// let rb = RingBuffer::<_, 1024>::new();
    /// let mut p = rb.producer().unwrap();
    /// let mut c = rb.consumer().unwrap();
    ///
    /// assert_eq!(c.slots(), 0);
    /// assert_eq!(p.push(0.0), Ok(()));
    /// assert_eq!(c.slots(), 1);
    /// ```
    pub fn slots(&self) -> usize {
        let (one, two) = self.slots_contiguous();
        one + two
    }

    /// Returns size of first contiguous chunk and
    /// the refreshed `tail` (if it has already been refreshed) and
    /// `true` if there may be another chunk at the beginning of the buffer.
    #[inline]
    fn slots_contiguous_helper(&self) -> (usize, Option<usize>, bool) {
        let b = &self.buffer;
        let mut head = self.cached_head.get();
        let mut collapsed_head = b.collapse_position(head);
        let mut tail = self.cached_tail.get();
        let mut collapsed_tail = b.collapse_position(tail);

        macro_rules! reset_skip {
            () => {
                // `skip` is never read in the producer thread, only written. Storing it before
                // `head` makes sure that we don't overwrite the producer's value prematurely.
                b.skip.store(b.capacity(), Ordering::Relaxed);
                head = b.increment(head, b.capacity() - collapsed_head);
                // Using `Release` here makes sure that storing `skip` "happens before".
                b.head.store(head, Ordering::Release);
                self.cached_head.set(head);
                collapsed_head = b.collapse_position(head);
                debug_assert_eq!(collapsed_head, 0);
            };
        }

        macro_rules! refresh_tail {
            () => {
                tail = b.tail.load(Ordering::Acquire);
                self.cached_tail.set(tail);
                collapsed_tail = b.collapse_position(tail);
            };
        }

        let mut is_empty = head == tail;
        if !is_empty && collapsed_tail <= collapsed_head {
            // NB: `skip` is only relevant if (collapsed) `tail < head`
            //     (or if the buffer is full).

            // `tail` has been refreshed since it last wrapped (even if `cached_tail` is outdated),
            // therefore `skip` needs no synchronization.
            let slots = b.skip.load(Ordering::Relaxed) - collapsed_head;
            if slots > 0 {
                (slots, None, true)
            } else {
                reset_skip!();
                // `tail` will not wrap around, but it might reveal a few more slots.
                refresh_tail!();
                (collapsed_tail, Some(tail), false)
            }
        } else {
            // `tail` might wrap around.
            refresh_tail!();
            is_empty = head == tail;
            if !is_empty && collapsed_tail <= collapsed_head {
                // Loading `skip` "happens after" loading `tail`.
                let slots = b.skip.load(Ordering::Relaxed) - collapsed_head;
                if slots > 0 {
                    (slots, Some(tail), true)
                } else {
                    reset_skip!();
                    (collapsed_tail, Some(tail), false)
                }
            } else {
                (collapsed_tail - collapsed_head, Some(tail), false)
            }
        }
    }

    /// Returns the number of slots of the next two contiguous segments available
    /// for reading with [`read_chunk()`](Consumer::read_chunk).
    ///
    /// In many cases, the second number will be `0`, but whenever the internal buffer
    /// wraps around, two contiguous segments might be available for reading.
    /// If the first number is `0`, the second will be `0` as well.
    ///
    /// The sum of both numbers is returned by [`slots()`](Consumer::slots).
    ///
    /// If you are only interested in the first number, using
    /// [`slots_contiguous_first()`](Consumer::slots_contiguous_first)
    /// should be slightly more efficient.
    ///
    /// The first number will also be reported via a [`ChunkError`] when calling
    /// [`read_chunk()`](Consumer::read_chunk) with a larger number.
    ///
    /// Since items can be concurrently produced on another thread, the actual number
    /// of available slots may increase at any time
    /// (up to a certain maximum that depends on the current read index and
    /// whether and how many slots have been skipped using
    /// [`Producer::write_chunk()`] or [`Producer::write_chunk_uninit()`],
    /// but at most up to the [`capacity()`](Consumer::capacity)).
    pub fn slots_contiguous(&self) -> (usize, usize) {
        let (slots, refreshed_tail, try_at_beginning) = self.slots_contiguous_helper();
        if !try_at_beginning {
            return (slots, 0);
        }
        let b = &self.buffer;
        let refreshed_tail = refreshed_tail.unwrap_or_else(|| {
            let tail = b.tail.load(Ordering::Acquire);
            self.cached_tail.set(tail);
            tail
        });
        (slots, b.collapse_position(refreshed_tail))
    }

    /// Returns the number of slots of the next contiguous segment available for reading with
    /// [`read_chunk()`](Consumer::read_chunk).
    ///
    /// This is the same as the first number returned by
    /// [`slots_contiguous()`](Consumer::slots_contiguous), but slightly more efficient.
    pub fn slots_contiguous_first(&self) -> usize {
        self.slots_contiguous_helper().0
    }

    /// Returns `true` if there are currently no slots available for reading.
    ///
    /// An empty ring buffer might cease to be empty at any time
    /// if the corresponding [`Producer`] is producing items in another thread.
    ///
    /// # Examples
    ///
    /// ```
    /// use rtrb::bip_array::RingBuffer;
    ///
    /// let rb = RingBuffer::<_, 1>::new();
    /// let mut p = rb.producer().unwrap();
    /// let mut c = rb.consumer().unwrap();
    ///
    /// assert!(c.is_empty());
    /// assert_eq!(p.push(0.0), Ok(()));
    /// assert!(!c.is_empty());
    /// ```
    ///
    /// Since items can be concurrently produced on another thread, the ring buffer
    /// might not be empty for long:
    ///
    /// ```
    /// # use rtrb::bip_array::RingBuffer;
    /// # let rb = RingBuffer::<_, 1>::new();
    /// # let mut p = rb.producer().unwrap();
    /// # let mut c = rb.consumer().unwrap();
    /// # assert_eq!(p.push(0.0), Ok(()));
    /// if c.is_empty() {
    ///     // The buffer might be empty, but it might as well not be
    ///     // if an item was just produced on another thread.
    /// }
    /// ```
    ///
    /// However, if it's not empty, another thread cannot change that:
    ///
    /// ```
    /// # use rtrb::bip_array::RingBuffer;
    /// # let rb = RingBuffer::<_, 1>::new();
    /// # let mut p = rb.producer().unwrap();
    /// # let mut c = rb.consumer().unwrap();
    /// # assert_eq!(p.push(0.0), Ok(()));
    /// if !c.is_empty() {
    ///     // At least one slot is guaranteed to be available for reading.
    /// }
    /// ```
    pub fn is_empty(&self) -> bool {
        self.next_head().is_none()
    }

    /// Returns the total capacity of the queue.
    ///
    /// See [`Producer::capacity()`] for more information.
    pub fn capacity(&self) -> usize {
        self.buffer.capacity()
    }

    /// Returns `true` if the [`RingBuffer`] connected to this `Consumer`
    /// is also connected to a [`Producer`].
    ///
    /// This can change at any time when another thread creates or drops a `Producer`.
    ///
    /// See also [`RingBuffer::has_producer()`].
    pub fn has_producer(&self) -> bool {
        self.buffer.flags.load(Ordering::SeqCst) & HAS_PRODUCER != 0
    }

    /// Get the `head` position for reading the next slot, if available.
    fn next_head(&self) -> Option<usize> {
        let (slots, _, _) = self.slots_contiguous_helper();
        if slots == 0 {
            None
        } else {
            Some(self.cached_head.get())
        }
    }

    /// Prepares a chunk of `n` slots for reading.
    ///
    /// [`ReadChunk::as_slice()`]
    /// provides immutable access to the slots.
    /// After reading from those slots, they explicitly have to be made available
    /// to be written again by the [`Producer`] by calling [`ReadChunk::commit()`]
    /// or [`ReadChunk::commit_all()`].
    ///
    /// Alternatively, items can be moved out of the [`ReadChunk`] using iteration
    /// because it implements [`IntoIterator`]
    /// ([`ReadChunk::into_iter()`] can be used to explicitly turn it into an [`Iterator`]).
    /// All moved items are automatically made available to be written again by
    /// the [`Producer`].
    ///
    /// # Errors
    ///
    /// If not enough slots are available, an error
    /// (containing the number of available slots) is returned.
    /// Use
    /// [`slots_contiguous_first()`](Consumer::slots_contiguous_first)
    /// to obtain the number of available slots beforehand.
    ///
    /// # Examples
    ///
    /// See the documentation of the [`chunks`](super::chunks#examples) module.
    pub fn read_chunk(&mut self, n: usize) -> Result<ReadChunk<'_, T>, ChunkError> {
        let b = &self.buffer;
        let (slots, _, _) = self.slots_contiguous_helper();
        if slots >= n {
            let offset = b.collapse_position(self.cached_head.get());
            // SAFETY: `offset` has been set to a valid position.
            Ok(unsafe { ReadChunk::new(self, n, offset) })
        } else {
            Err(ChunkError::TooFewSlots(slots))
        }
    }
}
