// Do not edit this file! It has been auto-generated from `codegen/templates/src/mod.rs`.
//! A bi-partite ring buffer whose elements are stored in an [array].
//!
//! See [`rtrb::bip_arc`] for a bi-partite ring buffer with dynamic storage.

/// A bounded single-producer single-consumer (SPSC) queue.
///
/// Elements can be written with a [`Producer`] and read with a [`Consumer`],
/// which can be obtained with ... TODO
///
/// *See also the [module-level documentation](rtrb::bip_array).*
pub struct RingBuffer<T, const N: usize> {
}

impl<T, const N: usize> RingBuffer<T, N> {
    pub fn producer(&self) -> Option<Producer<'_, N>> {
    }
}
