// DO NOT EDIT THIS FILE!
// It has been auto-generated from `codegen/templates/src/producer.rs.jinja`
// using the configuration file `codegen/configs/bip_array.toml`.

use core::cell::Cell;

use super::{
    chunks::{WriteChunk, WriteChunkUninit},
    ChunkError, PushError, RingBuffer,
};
use super::{HAS_CONSUMER, HAS_PRODUCER};
use crate::atomic::*;

// Only used in documentation:
#[allow(unused_imports)]
use super::Consumer;

/// The producer side of a [`RingBuffer`].
///
/// A `Producer` can be moved between threads,
/// but references from different threads are not allowed
/// (i.e. it is [`Send`] but not [`Sync`]).
///
/// Individual elements can be moved into the ring buffer with [`push()`](Producer::push),
/// multiple elements at once can be written with [`write_chunk()`](Producer::write_chunk)
/// and [`write_chunk_uninit()`](Producer::write_chunk_uninit).
///
/// The number of free slots currently available for writing can be obtained with
/// [`slots()`](Producer::slots).
///
/// A `Producer` can only be created with [`RingBuffer::producer()`].
#[derive(Debug, PartialEq, Eq)]
pub struct Producer<'a, T, const N: usize> {
    pub(super) buffer: &'a RingBuffer<T, N>,
    pub(super) cached_head: Cell<usize>,
    pub(super) cached_tail: Cell<usize>,
}

impl<T, const N: usize> Drop for Producer<'_, T, N> {
    fn drop(&mut self) {
        let _ = self.buffer.flags.fetch_and(!HAS_PRODUCER, Ordering::SeqCst);
    }
}

/// It can be moved ...
/// ```
/// use rtrb::bip_array::Producer;
/// fn assert_send<X: Send>() {}
/// assert_send::<Producer<u8, 8>>();
/// ```
/// ... but not shared between threads:
/// ```compile_fail
/// # use rtrb::bip_array::Producer;
/// fn assert_sync<X: Sync>() {}
/// assert_sync::<Producer<u8, 8>>();
/// ```
// SAFETY: After moving a producer to another thread, there is still only a single thread
// that can access the producer side of the queue.
unsafe impl<T: Send, const N: usize> Send for Producer<'_, T, N> where RingBuffer<T, N>: Sync {}

impl<T, const N: usize> Producer<'_, T, N> {
    /// Attempts to push an element into the queue.
    ///
    /// The element is *moved* into the ring buffer and its slot
    /// is made available to be read by the [`Consumer`].
    ///
    /// # Errors
    ///
    /// If the queue is full, the element is returned back as an error.
    ///
    /// # Examples
    ///
    /// ```
    /// use rtrb::bip_array::{PushError, RingBuffer};
    ///
    /// let rb = RingBuffer::<_, 1>::new();
    /// let mut p = rb.producer().unwrap();
    /// let mut c = rb.consumer().unwrap();
    ///
    /// assert_eq!(p.push(10), Ok(()));
    /// assert_eq!(p.push(20), Err(PushError::Full(20)));
    /// ```
    pub fn push(&mut self, value: T) -> Result<(), PushError<T>> {
        if let Some(tail) = self.next_tail() {
            let b = &self.buffer;
            // SAFETY: tail points to an empty slot.
            unsafe { b.slot_ptr(tail).write(value) };
            let tail = b.increment1(tail);
            b.tail.store(tail, Ordering::Release);
            self.cached_tail.set(tail);
            Ok(())
        } else {
            Err(PushError::Full(value))
        }
    }

    /// Returns the number of slots available for writing.
    ///
    /// Since items can be concurrently consumed on another thread, the actual number
    /// of available slots may increase at any time
    /// (up to the [`capacity()`](Producer::capacity)).
    ///
    /// To check for a single available slot,
    /// using [`is_full()`](Producer::is_full) is often quicker
    /// (because it might not have to check an atomic variable).
    ///
    /// Due to wrap-around of the internal buffer, the reported slots might not be
    /// on a contiguous segment and therefore not entirely available for writing with
    /// [`write_chunk()`](Producer::write_chunk) or
    /// [`write_chunk_uninit()`](Producer::write_chunk_uninit).
    /// To get the number of contiguous slots,
    /// [`slots_contiguous_first()`](Producer::slots_contiguous_first) or
    /// [`slots_contiguous_max()`](Producer::slots_contiguous_max) can be used.
    ///
    /// # Examples
    ///
    /// ```
    /// use rtrb::bip_array::RingBuffer;
    ///
    /// let rb = RingBuffer::<_, 4096>::new();
    /// let mut p = rb.producer().unwrap();
    /// let mut c = rb.consumer().unwrap();
    /// assert_eq!(p.push(0.5f32), Ok(()));
    ///
    /// assert_eq!(p.slots(), 4095);
    /// ```
    pub fn slots(&self) -> usize {
        let b = &self.buffer;
        let head = b.head.load(Ordering::Acquire);
        self.cached_head.set(head);
        b.capacity() - b.distance(head, self.cached_tail.get())
    }

    /// Returns size of first contiguous chunk and
    /// `true` if `head` has already been refreshed and
    /// `true` if there may be another chunk at the beginning of the buffer.
    // TODO: inline?
    fn slots_contiguous_helper(&self) -> (usize, bool, bool) {
        // TODO: code reuse with next_tail()?
        let b = &self.buffer;
        let mut head = self.cached_head.get();
        let tail = self.cached_tail.get();
        let is_empty = head == tail;
        let mut collapsed_head = b.collapse_position(head);
        let collapsed_tail = b.collapse_position(tail);
        if is_empty || collapsed_head < collapsed_tail {
            let slots = b.capacity() - collapsed_tail;
            debug_assert!(slots != 0 || b.capacity() == 0);
            return (slots, false, true);
        }
        head = b.head.load(Ordering::Acquire);
        self.cached_head.set(head);
        collapsed_head = b.collapse_position(head);
        if collapsed_head < collapsed_tail {
            let slots = b.capacity() - collapsed_tail;
            debug_assert!(slots != 0 || b.capacity() == 0);
            return (slots, true, true);
        }
        (collapsed_head - collapsed_tail, true, false)
    }

    /// Returns the number of slots of the next two contiguous segments available
    /// for writing with [`write_chunk()`](Producer::write_chunk) or
    /// [`write_chunk_uninit()`](Producer::write_chunk_uninit).
    ///
    /// When a chunk larger than the first segment is written
    /// (assuming the second number is large enough to allow that),
    /// the first segment is skipped,
    /// effectively reducing the maximum available [`Consumer::slots()`]
    /// (until the segment is overwritten again at a later point).
    ///
    /// In many cases, the second number will be `0`, but whenever the internal buffer
    /// wraps around, two contiguous segments might be available for writing.
    /// If the first number is `0`, the second will be `0` as well.
    ///
    /// If you are only interested in the first number, using
    /// [`slots_contiguous_first()`](Producer::slots_contiguous_first)
    /// should be slightly more efficient.
    ///
    /// The sum of both numbers is returned by [`slots()`](Producer::slots), their maximum
    /// is returned by [`slots_contiguous_max()`](Producer::slots_contiguous_max).
    ///
    /// Since items can be concurrently consumed on another thread, the actual number
    /// of available slots may increase at any time
    /// (up to the [`capacity()`](Producer::capacity)).
    // TODO: inline?
    pub fn slots_contiguous(&self) -> (usize, usize) {
        let (slots, refreshed, try_at_beginning) = self.slots_contiguous_helper();
        // TODO: return Some(head) instead of refreshed?
        if !try_at_beginning {
            return (slots, 0);
        }
        let b = &self.buffer;
        let head;
        if refreshed {
            head = self.cached_head.get();
        } else {
            head = b.head.load(Ordering::Acquire);
            self.cached_head.set(head);
        }
        (slots, b.collapse_position(head))
    }

    /// Returns the number of slots of the next contiguous segment available for writing with
    /// [`write_chunk()`](Producer::write_chunk) or
    /// [`write_chunk_uninit()`](Producer::write_chunk_uninit).
    ///
    /// This is the same as the first number returned by
    /// [`slots_contiguous()`](Producer::slots_contiguous), but slightly more efficient.
    ///
    /// If you want to avoid skipping any slots, you should use this method instead of
    /// [`slots_contiguous_max()`](Producer::slots_contiguous_max).
    // TODO: inline?
    pub fn slots_contiguous_first(&self) -> usize {
        self.slots_contiguous_helper().0
    }

    /// Convenience function to obtain the maximum of the two values returned by
    /// [`slots_contiguous()`](Producer::slots_contiguous).
    ///
    /// This number will also be reported via a [`ChunkError`] when calling
    /// [`write_chunk()`](Producer::write_chunk) or
    /// [`write_chunk_uninit()`](Producer::write_chunk_uninit) with a larger number.
    ///
    /// If you want to avoid skipping any slots, you should use
    /// [`slots_contiguous_first()`](Producer::slots_contiguous_first) instead.
    // TODO: inline?
    pub fn slots_contiguous_max(&self) -> usize {
        let (one, two) = self.slots_contiguous();
        one.max(two)
    }

    /// Returns `true` if there are currently no slots available for writing.
    ///
    /// A full ring buffer might cease to be full at any time
    /// if the corresponding [`Consumer`] is consuming items in another thread.
    ///
    /// # Examples
    ///
    /// ```
    /// use rtrb::bip_array::RingBuffer;
    ///
    /// let rb = RingBuffer::<_, 1>::new();
    /// let mut p = rb.producer().unwrap();
    /// let mut c = rb.consumer().unwrap();
    ///
    /// assert!(!p.is_full());
    /// assert_eq!(p.push(10), Ok(()));
    /// assert!(p.is_full());
    /// ```
    ///
    /// Since items can be concurrently consumed on another thread, the ring buffer
    /// might not be full for long:
    ///
    /// ```
    /// # use rtrb::bip_array::RingBuffer;
    /// # let rb = RingBuffer::<_, 1>::new();
    /// # let mut p = rb.producer().unwrap();
    /// # let mut c = rb.consumer().unwrap();
    /// # assert_eq!(p.push(10), Ok(()));
    /// if p.is_full() {
    ///     // The buffer might be full, but it might as well not be
    ///     // if an item was just consumed on another thread.
    /// }
    /// ```
    ///
    /// However, if it's not full, another thread cannot change that:
    ///
    /// ```
    /// # use rtrb::bip_array::RingBuffer;
    /// # let rb = RingBuffer::<_, 1>::new();
    /// # let mut p = rb.producer().unwrap();
    /// # let mut c = rb.consumer().unwrap();
    /// # assert_eq!(p.push(10), Ok(()));
    /// if !p.is_full() {
    ///     // At least one slot is guaranteed to be available for writing.
    /// }
    /// ```
    ///
    /// A ring buffer (of the Bip Buffer variety) can be full even if it contains
    /// fewer items than its [`capacity()`](Producer::capacity()).
    ///
    /// ```
    /// use std::io::{Read, Write};
    /// use rtrb::bip_array::RingBuffer;
    ///
    /// let rb = RingBuffer::<_, 8>::new();
    /// let mut p = rb.producer().unwrap();
    /// let mut c = rb.consumer().unwrap();
    /// assert_eq!(p.write(&[1, 2, 3, 4, 5]).unwrap(), 5);
    /// let mut a = [0; 4];
    /// assert_eq!(c.read(&mut a).unwrap(), 4);
    /// assert_eq!(a, [1, 2, 3, 4]);
    /// // This will skip 3 slots:
    /// assert_eq!(p.write(&[4, 3, 2, 1]).unwrap(), 4);
    /// assert!(p.is_full());
    /// assert_eq!(p.capacity(), 8);
    /// assert_eq!(p.slots(), 0);
    /// assert_eq!(c.slots(), 5);
    /// ```
    pub fn is_full(&self) -> bool {
        self.next_tail().is_none()
    }

    /// Returns the total capacity of the queue.
    ///
    /// At any time, the capacity is subdivided into
    /// [`Producer::slots()`] available for writing and
    /// [`Consumer::slots()`] available for
    /// reading, as well as potentially some slots that have been skipped in
    /// [`Producer::write_chunk`] or [`Producer::write_chunk_uninit`].
    ///
    /// # Examples
    ///
    /// ```
    /// use rtrb::bip_array::RingBuffer;
    ///
    /// let rb = RingBuffer::<_, 4096>::new();
    /// let mut p = rb.producer().unwrap();
    /// let mut c = rb.consumer().unwrap();
    ///
    /// assert_eq!(p.push(-0.7), Ok(()));
    /// assert_eq!(p.slots(), 4095);
    /// assert_eq!(c.slots(), 1);
    /// assert_eq!(p.capacity(), 4096);
    /// assert_eq!(c.capacity(), 4096);
    /// ```
    pub fn capacity(&self) -> usize {
        self.buffer.capacity()
    }

    /// Returns `true` if the [`RingBuffer`] connected to this `Producer`
    /// is also connected to a [`Consumer`].
    ///
    /// This can change at any time when another thread creates or drops a `Consumer`.
    ///
    /// See also [`RingBuffer::has_consumer()`].
    pub fn has_consumer(&self) -> bool {
        self.buffer.flags.load(Ordering::SeqCst) & HAS_CONSUMER != 0
    }

    /// Get the tail position for writing the next slot, if available.
    ///
    /// This is a strict subset of the functionality implemented in `write_chunk_uninit()`.
    /// For performance, this special case is implemented separately.
    fn next_tail(&self) -> Option<usize> {
        let head = self.cached_head.get();
        let tail = self.cached_tail.get();
        let b = &self.buffer;
        // Check if the queue is *possibly* full.
        if b.distance(head, tail) == b.capacity() {
            // Refresh the head ...
            let head = b.head.load(Ordering::Acquire);
            self.cached_head.set(head);
            // ... and check if it's *really* full.
            if b.distance(head, tail) == b.capacity() {
                // `head` didn't change, the buffer is definitely full.
                return None;
            }
        }
        Some(tail)
    }

    /// Prepares a chunk of `n` slots (initially containing their [`Default`] value)
    /// for writing.
    ///
    /// [`WriteChunk::as_mut_slice()`]
    /// provides mutable access to the slots.
    /// After writing to those slots, they explicitly have to be made available
    /// to be read by the [`Consumer`] by calling [`WriteChunk::commit()`]
    /// or [`WriteChunk::commit_all()`].
    ///
    /// For an alternative that does not require the trait bound [`Default`],
    /// see [`Producer::write_chunk_uninit()`].
    ///
    /// If items are supposed to be moved from an iterator into the ring buffer,
    /// [`Producer::write_chunk_uninit()`] followed by [`WriteChunkUninit::fill_from_iter()`]
    /// can be used.
    ///
    /// # Errors
    ///
    /// If not enough slots are available, an error
    /// (containing the number of available slots) is returned.
    /// Use
    /// [`slots_contiguous_max()`](Producer::slots_contiguous_max) (or
    /// [`slots_contiguous_first()`](Producer::slots_contiguous_first))
    /// to obtain the number of available slots beforehand.
    ///
    /// # Examples
    ///
    /// See the documentation of the [`chunks`](crate::chunks#examples) module.
    pub fn write_chunk(&mut self, n: usize) -> Result<WriteChunk<'_, T, N>, ChunkError>
    where
        T: Default,
    {
        self.write_chunk_uninit(n).map(WriteChunk::from)
    }

    /// Prepares a chunk of `n` (uninitialized) slots for writing.
    ///
    /// [`WriteChunkUninit::as_mut_slice()`]
    /// provides mutable access
    /// to the uninitialized slots.
    /// After writing to those slots, they explicitly have to be made available
    /// to be read by the [`Consumer`] by calling [`WriteChunkUninit::commit()`]
    /// or [`WriteChunkUninit::commit_all()`].
    ///
    /// Alternatively, [`WriteChunkUninit::fill_from_iter()`] can be used
    /// to move items from an iterator into the available slots.
    /// All moved items are automatically made available to be read by the [`Consumer`].
    ///
    /// # Errors
    ///
    /// If not enough slots are available, an error
    /// (containing the number of available slots) is returned.
    /// Use
    /// [`slots_contiguous_max()`](Producer::slots_contiguous_max) (or
    /// [`slots_contiguous_first()`](Producer::slots_contiguous_first))
    /// to obtain the number of available slots beforehand.
    ///
    /// # Safety
    ///
    /// This function itself is safe, as is [`WriteChunkUninit::fill_from_iter()`].
    /// However, when using
    /// [`WriteChunkUninit::as_mut_slice()`],
    /// the user has to make sure that the relevant slots have been initialized
    /// before calling [`WriteChunkUninit::commit()`] or [`WriteChunkUninit::commit_all()`].
    ///
    /// For a safe alternative that provides
    /// a mutable slice    /// of [`Default`]-initialized slots, see [`Producer::write_chunk()`].
    #[rustfmt::skip]
    pub fn write_chunk_uninit(&mut self, n: usize) -> Result<WriteChunkUninit<'_, T, N>, ChunkError> {
        let b = &self.buffer;
        let (mut slots, refreshed, try_at_beginning) = self.slots_contiguous_helper();
        if slots >= n {
            let offset = b.collapse_position(self.cached_tail.get());
            // SAFETY: `offset` has been set to a valid position.
            return Ok(unsafe { WriteChunkUninit::new(self, n, offset) });
        } else if try_at_beginning {
            // TODO: get refreshed_head.or_else(self.cached_head.get)
            let mut head = self.cached_head.get();
            let mut collapsed_head = b.collapse_position(head);
            if collapsed_head >= n {
                // SAFETY: 0 is a valid position.
                return Ok(unsafe { WriteChunkUninit::new(self, n, 0) });
            }
            // TODO: refreshed_head.is_none()
            if !refreshed {
                head = b.head.load(Ordering::Acquire);
                self.cached_head.set(head);
                collapsed_head = b.collapse_position(head);
                if collapsed_head >= n {
                    // SAFETY: 0 is a valid position.
                    return Ok(unsafe { WriteChunkUninit::new(self, n, 0) });
                }
            }
            slots = slots.max(collapsed_head);
        }
        Err(ChunkError::TooFewSlots(slots))
    }
}
