// Do not edit this file! It has been auto-generated from `codegen/templates/src/mod.rs`.

//! Ring buffer using a virtual memory trick.
//!
//! Phil Howard is maybe the inventor (2001?):
//! <http://web.archive.org/web/20190208212054/http://freshmeat.sourceforge.net/projects/vrb/>
//!
//! <http://web.archive.org/web/20140705114711/http://vrb.sourceforge.net/>
//!
//! code available here (as part of LIBH): <https://web.archive.org/web/20140625200016/http://libh.slashusr.org/>
//!
//! Potential Windows solution:
//! <https://fgiesen.wordpress.com/2012/07/21/the-magic-ring-buffer/>
//!
//! ... `capacity` will be rounded up to page size ... (TODO: add this in constructor docs?)
//!
//! # Usage
//!
//! A [`RingBuffer`] consists of two parts:
//! a [`Producer`] for writing into the ring buffer and
//! a [`Consumer`] for reading from the ring buffer.
//!
//! TODO: more usage instructions

mod ring_buffer;
pub use ring_buffer::RingBuffer;
mod producer;
pub use producer::Producer;
mod consumer;
pub use consumer::Consumer;
mod arc_ring_buffer;

pub mod chunks;

// Only used in documentation:
#[allow(unused_imports)]
use chunks::WriteChunkUninit;

/// Error type for [`Consumer::peek()`].
#[doc(inline)]
pub use crate::PeekError;

/// Error type for [`Consumer::pop()`].
#[doc(inline)]
pub use crate::PopError;

/// Error type for [`Producer::push()`].
#[doc(inline)]
pub use crate::PushError;

/// Error type for [`Producer::write_chunk()`], [`Producer::write_chunk_uninit()`]
/// and [`Consumer::read_chunk()`].
///
/// To get the maximum number of available slots beforehand
/// (and therefore avoid this error), use
/// [`Producer::slots()`] and [`Consumer::slots()`],
/// respectively.
#[doc(inline)]
pub use crate::ChunkError;

/// Extension trait providing a [`copy_to_uninit()`](CopyToUninit::copy_to_uninit)
/// method on built-in slices.
///
/// This can be used to safely copy data to the
/// slice returned from [`WriteChunkUninit::as_mut_slice()`].
///
/// To use this, the trait has to be brought into scope, e.g. with:
///
/// ```
/// use rtrb::vrb_arc2::CopyToUninit as _;
/// ```
///
/// TODO: update link:
///
/// For a usage example, see [`crate::chunks`](crate::chunks#common-access-patterns).
#[doc(inline)]
pub use crate::CopyToUninit;